# -*- coding: utf-8 -*-
import sys, json
sys.path.insert(0,'/home/claude/pet/analysis/rev/doc')
from common import newdoc, mk
from docx.enum.text import WD_ALIGN_PARAGRAPH
R=json.load(open('/home/claude/pet/analysis/rev/out/results.json'))
D=R['dataset']; T=R['topology']; S=R['saturation']

doc=newdoc(); P,RICH,H,HANG,TABLE=mk(doc)

# ---------------- Title page ----------------
P('',indent=False)
t=doc.add_paragraph(); t.alignment=WD_ALIGN_PARAGRAPH.CENTER
r=t.add_run('Chromosomal phosphoethanolamine transferases as repeated and independent sources of mobilised colistin resistance in Enterobacterales'); r.bold=True
P('',indent=False)
P('Running title: Chromosomal origins of mcr genes',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
P('',indent=False)
P('Author names and affiliations',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False,bold=True)
P('[Author 1]1*, [Author 2]1, [Author 3]2',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
P('1 [Department], [Institution], [City], [Country]',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
P('2 [Department], [Institution], [City], [Country]',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
P('* Correspondence: [email]',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
doc.add_page_break()

# ---------------- Abstract ----------------
H('Abstract')
AB1="The mobilised colistin resistance ("
AB2=") gene families encode phosphoethanolamine transferases that are structurally and functionally equivalent to chromosomal EptA. Where each family came from, and which chromosomal genes might be recruited next, remain only partly resolved. We assembled 191 proteins, comprising 150 chromosomal transferases retrieved from RefSeq across 44 genera of "
AB3=" and of taxa implicated as donors, 28 unclustered records from UniProtKB, the reference allele of every named "
AB4=(" family that has a reference allele in the catalogue, eleven of the twelve named to date, and five members of the wider alkaline phosphatase superfamily, four of them used to root the tree, less three records that proved to be exact duplicates. Maximum-likelihood inference under a selected model placed the mobilised proteins in nine separate lineages of the EptA clade in the primary analysis of 161 sequences, and in ten when the unclustered records were added and the tree was rooted on the outgroup. A constrained tree enforcing their monophyly was rejected by the approximately unbiased test at p = {pau}, so a single origin can be excluded and the topologies place the number of separate capture events at nine or ten. Unclustered searching identified closer chromosomal relatives than clustered searching had, by as much as 36 percentage points, and two chromosomal records proved identical to catalogued alleles over their full length, one in ").format(pau='8.1 x 10-6')
AB5=" and one in "
AB6=(". Six positions of the catalytic apparatus were invariant across every sequence examined, and the ten that vary were reconstructed at the node each mobilised lineage shares with its chromosomal relatives, where the six disulfide-forming cysteines, Lys333 and His478 were recovered with posterior probability 1.00 at all nine nodes. Synonymous sites were saturated between families, with dS above one in {a} of {b} comparisons, so selection was assessed within families, where the ratio of non-synonymous to synonymous change ran from 0.08 to 0.64. Profile searches built from catalogued alleles reached only three of 178 chromosomal and related proteins, all of them at least 95% identical to an allele of a well-catalogued family, and missed proteins 80% to 90% identical as well as one identical to MCR-6.1. The enzymes were complete before mobilisation. What changed was their genomic setting, and a pool of near-identical chromosomal genes sits beyond the reach of reference-based surveillance.").format(a=S['n_dS_gt1'],b=S['n_pairs'])
RICH([(AB1,False),('mcr',True),(AB2,False),('Enterobacterales',True),(AB3,False),('mcr',True),(AB4,False),('Moraxella',True),(AB5,False),('Aeromonas',True),(AB6,False)],indent=False)
P('',indent=False)
RICH([('Keywords: ',False),('mcr',True),(', colistin resistance, phosphoethanolamine transferase, ',False),('eptA',True),(', comparative genomics, horizontal gene transfer, One Health',False)],indent=False)
doc.add_page_break()

# ---------------- Introduction ----------------
H('1. Introduction')
RICH([('Colistin returned to clinical use because there was little else left. Decades after it had been abandoned on grounds of nephrotoxicity, the spread of carbapenem-resistant ',False),('Enterobacterales',True),(' forced clinicians back onto the polymyxins for infections that no longer responded to anything else (Poirel, Jayol, and Nordmann, 2017). Resistance was for a long time thought to arise only through chromosomal mutation, and therefore to stay within the lineage in which it appeared. That assumption ended with the description of ',False),('mcr-1',True),(' on a conjugative plasmid in ',False),('Escherichia coli',True),(' from Chinese pigs (Liu et al., 2016). Eleven further families have since been named, from mcr-2 to mcr-12 (Xavier et al., 2016; Carattoli et al., 2017; Yin et al., 2017; X. Wang et al., 2018; Yang et al., 2018; Carroll et al., 2019; C. Wang et al., 2020), and they have been found in food animals, in retail meat, in environmental water and in patients on four continents.',False)])
RICH([('All ',False),('mcr',True),(' products belong to the alkaline phosphatase superfamily and act as phosphoethanolamine transferases. They attach a phosphoethanolamine group to the 1 and 4′ phosphates of lipid A, which lowers the net negative charge of the outer membrane and weakens the electrostatic attraction that the polymyxins depend on. The same chemistry is performed by chromosomal enzymes that long predate the clinical use of colistin. EptA modifies lipid A, EptB modifies the outer 3-deoxy-D-',False),('manno',True),('-octulosonic acid residue of the inner core (Reynolds et al., 2005), CptA modifies the heptose of the core, and EptC of ',False),('Campylobacter jejuni',True),(' modifies both lipid A and the flagellar rod protein FlgG (Cullen et al., 2012). In ',False),('Neisseria meningitidis',True),(' the homologue LptA is required for resistance to polymyxin (Tzeng et al., 2005; Wanty et al., 2013).',False)])
RICH([('Structural work has shown how close the relationship is. The periplasmic domain of MCR-1 adopts the alkaline phosphatase fold, binds zinc, and uses a threonine nucleophile that becomes transiently phosphorylated during catalysis (Hu et al., 2016; Ma et al., 2016). The catalytic domain of MCR-2 has the same arrangement (Coates et al., 2017), and so does the EptC homologue of E. coli, which binds zinc in the same way but lacks the disulfide bonds and does not confer resistance (Zhao et al., 2019). The fold, the metal site and the nucleophile are also present in the neisserial LptA (Wanty et al., 2013). Nothing in the enzyme distinguishes a mobilised transferase from a chromosomal one. What distinguishes them is the DNA around the gene.',False)])
RICH([('Individual donors have been proposed for several families. ',False),('Moraxella',True),(' species carry chromosomal genes close enough to ',False),('mcr-1',True),(' and ',False),('mcr-2',True),(' to be regarded as their probable source (AbuOun et al., 2017; Kieffer et al., 2017), and ',False),('mcr-4',True),(' was noted on discovery to resemble a chromosomal protein of ',False),('Shewanella frigidimarina',True),(' (Carattoli et al., 2017). Those observations were made one family at a time, against whichever sequences were available when each family was described. They have not been brought together in a single analysis, and three questions have therefore stayed open. Do the families share one origin or many? Was the catalytic machinery complete before mobilisation or assembled after it? And which chromosomal genes are close enough to the mobilised ones to be plausible sources of the next event?',False)])
RICH([('This study addresses those questions. Chromosomal phosphoethanolamine transferases were retrieved across the breadth of the ',False),('Enterobacterales',True),(' and from the taxa implicated as donors, analysed together with the reference alleles of the eleven ',False),('mcr',True),(' families that have one and with an outgroup from the wider superfamily, and examined for phylogenetic placement, for the conservation of the catalytic apparatus, for ancestral state at the nodes where mobilisation must have occurred, for the strength of selection, for genomic context, and for whether reference-based surveillance would detect them.',False)])

# ---------------- Methods ----------------
H('2. Materials and Methods')

H('2.1. Reference alleles of the mobilised families',3)
RICH([('Nucleotide sequences for the reference allele of each ',False),('mcr',True),(' family were taken from the NCBI Bacterial Antimicrobial Resistance Reference Gene Catalog (Feldgarden et al., 2021) as distributed with ABRicate v1.0.1 (https://github.com/tseemann/abricate, database snapshot of 2024-01-24). Every family holding a reference allele in that release was included. This gave ',False),('mcr-1.1',True),(' (NG_050417.1), ',False),('mcr-2.1',True),(' (NG_051171.1), ',False),('mcr-3.1',True),(' (NG_055505.1), ',False),('mcr-4.1',True),(' (NG_057470.1), ',False),('mcr-5.1',True),(' (NG_055658.1), ',False),('mcr-6.1',True),(' (NG_055781.1), ',False),('mcr-7.1',True),(' (NG_056413.1), ',False),('mcr-8.1',True),(' (NG_061399.1), ',False),('mcr-10.1',True),(' (NG_066767.1) and ',False),('mcr-12.1',True),(' (NG_245195.1). The catalogue holds no entry for ',False),('mcr-11',True),(', which could therefore not be included, and no entry for ',False),('mcr-9',True),(' under that designation, so the reference allele of ',False),('mcr-9',True),(' was taken from the original description (MK070339; Carroll et al., 2019). All eleven sequences translated without internal stop codons. For the analyses of selection within families, every allele of each family held in the same catalogue release was retrieved, giving 37 alleles of ',False),('mcr-1',True),(', 41 of ',False),('mcr-3',True),(', nine of ',False),('mcr-4',True),(', eight of ',False),('mcr-2',True),(', six each of ',False),('mcr-8',True),(' and ',False),('mcr-10',True),(', and five of ',False),('mcr-5',True),('.',False)])

H('2.2. Chromosomal and related transferases',3)
RICH([('Chromosomal homologues were retrieved from the NCBI RefSeq non-redundant protein collection (O’Leary et al., 2016) using 45 taxon queries, 35 of them genus-level taxa of ',False),('Enterobacterales',True),(' and ten of taxa outside the order that have been implicated as donors or that carry well-characterised paralogues, namely ',False),('Moraxella',True),(', ',False),('Faucicola',True),(' (into which ',False),('Moraxella osloensis',True),(' has been transferred on taxogenomic grounds; Sbissi et al., 2025; T\u00f8njum et al., 2026), ',False),('Acinetobacter',True),(', ',False),('Shewanella',True),(', ',False),('Aeromonas',True),(', ',False),('Vibrio',True),(', ',False),('Neisseria',True),(', ',False),('Campylobacter',True),(', ',False),('Pseudomonas',True),(' and ',False),('Burkholderia',True),('. Records were retained if the annotation identified a phosphoethanolamine transferase, a lipid A phosphoethanolamine transferase or a sulfatase-family protein of the appropriate length. Within each query the retained records were clustered at approximately 80% identity and one representative was kept, which gave 150 chromosomal proteins. The 45 queries and the 150 retained proteins are not in one-to-one correspondence. Retention was decided on annotation rather than on the query taxon, so records of a few genera outside the query list were returned and kept, among them Cupriavidus. The retained set represents 44 genera, and 22 of the records carry annotation only above genus level.',False)])
RICH([('Clustering was used for retrieval only. Because it can remove the closest relative of a mobilised allele, the identity analyses were repeated against an unclustered set. Every reviewed and unreviewed UniProtKB (UniProt Consortium, 2025) entry annotated as a phosphoethanolamine transferase, an EptA-like protein or an MCR-like protein was retrieved for ',False),('Moraxella',True),(', ',False),('Faucicola',True),(', ',False),('Shewanella',True),(', ',False),('Aeromonas',True),(', ',False),('Kluyvera',True),(' and ',False),('Buttiauxella',True),(', giving 28 further sequences. Five members of the wider alkaline phosphatase superfamily of ',False),('E. coli',True),(' were added to root the tree: OpgB (P39401), AslA (P25549), YidJ (P31447) and YdeN (P77318) as outgroup, and OpgE (P75785) as a reference for the paralogue group described below. After removal of three sequences that were exact duplicates of others already present, the working dataset held 191 proteins. The 161-sequence subset made up of the RefSeq proteins and the reference alleles was used for the primary phylogenetic analysis, and the full 191-sequence set for the identity analyses and for a rooted reanalysis.',False)])
RICH([('One sequence, WP_261396260.1 of ',False),('Citrobacter freundii',True),(', is 400 residues against a median of 546 across the chromosomal and related proteins and is the only record below 450. It was retained in the alignment and the tree, where its placement is informative, and excluded from every calculation of identity to a mobilised allele and from the ranking of candidate donors.',False)])

H('2.3. Alignment and phylogenetic inference',3)
RICH([('Proteins were aligned with FAMSA (Deorowicz et al., 2016) as implemented in pyfamsa v0.7.0. The 161-sequence alignment held 808 columns and the 191-sequence alignment 1038. Poorly aligned positions were removed with trimAl (Capella-Gutiérrez et al., 2009) in pytrimal v0.8.5 under the automated1 heuristic, leaving 313 and 444 columns respectively. Maximum-likelihood trees were inferred with IQ-TREE v2.3.6 (Minh et al., 2020). Model selection used ModelFinder (Kalyaanamoorthy et al., 2017) across the LG, WAG, JTT, VT, Blosum62, Dayhoff, cpREV, rtREV and PMB matrices, each with and without empirical amino acid frequencies, with and without a proportion of invariant sites, and with discrete gamma and free-rate models of among-site rate variation. LG+F+I+R6, which combines the LG exchangeability matrix (Le and Gascuel, 2008) with empirical frequencies, a proportion of invariant sites and six free rate categories, was selected by the Bayesian information criterion and used for the primary analysis. Branch support came from 1000 ultrafast bootstrap replicates (Hoang et al., 2018) and 1000 replicates of the SH-like approximate likelihood ratio test (Guindon et al., 2010). The expanded alignment was analysed under LG+F+R4 with the four superfamily proteins constrained as the outgroup; the simplified rate model was used to keep the larger analysis tractable.',False)])
RICH([('Monophyly of the mobilised families was tested explicitly. A constraint tree placing the eleven mobilised proteins in one clade and leaving the remaining relationships unresolved was supplied to a second maximum-likelihood search under the same model. The search was stopped after 60 rounds of topology optimisation, at which point successive improvements had fallen below one log-likelihood unit. The constrained and unconstrained trees were then compared on the same alignment with the approximately unbiased test (Shimodaira, 2002), the Kishino-Hasegawa and Shimodaira-Hasegawa tests and their weighted variants, and the expected likelihood weight, using 10,000 RELL replicates.',False)])

H('2.4. Identity, domain architecture and active-site mapping',3)
RICH([('Pairwise amino acid identity was calculated over columns at which both sequences carried a residue in the untrimmed alignment of the 191-sequence set. Hydropathy was computed on the Kyte and Doolittle scale over a sliding window of 19 residues; contiguous runs with a mean above 1.6 were merged and counted as predicted membrane-spanning segments. Sixteen positions reported from the MCR-1 crystal structures (Hu et al., 2016; Ma et al., 2016) were mapped through the alignment with Biopython v1.88 (Cock et al., 2009) and their occupancy tabulated. Six of the sixteen carry the same residue in every sequence in the dataset and are therefore uninformative for any comparison between groups; the remaining ten vary and are treated separately throughout.',False)])

H('2.5. Ancestral sequence reconstruction',3)
RICH([('Marginal ancestral states were reconstructed with IQ-TREE on the untrimmed alignment under the selected model, with the topology and branch lengths of the maximum-likelihood tree held fixed. For each mobilised lineage the state was read at the stem node, that is at the node the lineage shares with its chromosomal relatives, rather than at the crown of the mobilised clade. Reconstruction was repeated on the outgroup-rooted topology of the 191-sequence analysis to check that the result did not depend on the position of the root. States are reported only for the ten positions that vary in the dataset, with their posterior probabilities.',False)])

H('2.6. Selection',3)
RICH([('Codon alignments were generated by threading coding sequences onto the corresponding protein alignments. Rates of synonymous and non-synonymous substitution were estimated by maximum likelihood with codeml from PAML v4.10.10 (Yang, 2007) under the F3x4 codon frequency model. Pairwise estimates between families were used first to establish whether synonymous sites retained usable information. They did not, so between-family estimates are not reported. Within families, where synonymous divergence is low, the one-ratio model M0 was fitted to each allele alignment on a neighbour-joining topology. For mcr-1, the family with the largest set of closely related alleles, site models were fitted and compared by likelihood ratio test, M1a against M2a and M7 against M8 (Yang et al., 2000), with posterior identification of sites by the Bayes empirical Bayes procedure. Results from the site models are interpreted with the limits on accuracy and power at low divergence in mind (Anisimova et al., 2002).',False)])

H('2.7. Genomic context and mobile elements',3)
RICH([('Genomic context was examined for the original deposits of ',False),('mcr-1',True),(' (KP347127), ',False),('mcr-2',True),(' (LT598652), ',False),('mcr-4',True),(' (MF543359), ',False),('mcr-5',True),(' (KY807921), ',False),('mcr-7.1',True),(' (MG267386) and ',False),('mcr-8',True),(' (MG736312), and for four chromosomal donor loci. Annotated flat files were taken from the European Nucleotide Archive and features were read within a window extending approximately 10 kb either side of the transferase gene. Predicted open reading frames from the chromosomal windows were searched against the transposase profile hidden Markov models distributed with ISEScan (Xie and Tang, 2017) using pyhmmer v0.12.3 (Eddy, 2011). The window is narrower than the 30 to 50 kb used in dedicated studies of composite transposons, and the negative results below are reported as properties of that window.',False)])

H('2.8. Detection by reference-based methods',3)
RICH([('To test whether current surveillance would recognise the chromosomal homologues, profile hidden Markov models were built from the catalogued allele sets of the ',False),('mcr',True),(' families. The NCBI and ResFinder catalogues together hold 219 alleles across eleven families. A profile was built for each of the eight families with at least three alleles, which are ',False),('mcr-1',True),(', ',False),('mcr-2',True),(', ',False),('mcr-3',True),(', ',False),('mcr-4',True),(', ',False),('mcr-5',True),(', ',False),('mcr-8',True),(', ',False),('mcr-9',True),(' and ',False),('mcr-10',True),('. The three remaining families hold one or two alleles each and cannot be modelled, which is itself part of the result. For each family the detection threshold was set at the lowest score achieved by a catalogued allele of that family, which is the most permissive threshold a reference-based tool could adopt without admitting members of other families. The 176 chromosomal and related proteins of the dataset were scored against all profiles, together with the two records that had been removed as exact duplicates of mobilised alleles, 178 in all.',False)])

H('2.9. Data and code availability',3)
P('All sequences analysed are public records held by NCBI, the European Nucleotide Archive and UniProtKB. Accessions for the chromosomal and related proteins, with their ranking by identity to the closest mobilised family, are given in Supplementary Table S1, and accessions for the mobilised alleles are given in section 2.1. The analysis scripts are deposited at [repository URL] and archived with the persistent identifier [DOI]. The trimmed and untrimmed alignments, the maximum-likelihood tree with both support measures, the ultrafast bootstrap replicates, the constrained tree, the output of the topology tests, the reconstructed ancestral states and the codeml output files accompany this article as named additional files. Each figure legend ends with the name of the script that produced it.',indent=False)

# ---------------- Results ----------------
H('3. Results')

H('3.1. Three paralogue groups, with every mobilised family in one of them',3)
RICH([('The 161 proteins of the primary analysis resolved into three groups corresponding to the three ',False),('E. coli',True),(' paralogues (Figure 1). The group anchored by EptA held 76 sequences, 65 of them chromosomal and 11 mobilised. The group anchored by EptB held 36 and the group anchored by CptA held 49. No sequence fell outside the three. Support for the groups was uneven: the CptA group had 99.3 SH-aLRT and 100 ultrafast bootstrap, the EptB group 47.7 and 96, and the EptA group 73.7 and 61. The weakness of the last value reflects the difficulty of resolving the deepest split in a family this divergent, and it is the reason the claims below rest on tests rather than on support values alone.',False)])
RICH([('The group anchored by CptA is not homogeneous. When OpgE of ',False),('E. coli',True),(' (P75785) was added, 35 of the 49 sequences fell with it and only 14 with CptA and EptC. OpgE modifies osmoregulated periplasmic glucans rather than lipopolysaccharide, so 35 of the 150 chromosomal transferases, just under a quarter, act on a substrate that has nothing to do with the charge of the outer membrane. That distinction matters for interpreting the active-site tables below, and we keep the two subgroups separate from this point on.',False)])

H('3.2. The mobilised families do not form a clade',3)
RICH([('Within the EptA group the mobilised proteins were scattered among chromosomal sequences rather than clustered. Nine separate lineages were recovered. MCR-1.1, MCR-2.1 and MCR-6.1 formed a single clade with 95.8 SH-aLRT and 100 ultrafast bootstrap, and within it MCR-2.1 and MCR-6.1 were sisters at 91.2 and 100. MCR-3.1 and MCR-7.1 both sat inside a clade of chromosomal ',False),('Aeromonas',True),(' proteins but were separated from each other by those proteins, at 97.7 and 100 and at 98.4 and 100 respectively. MCR-5.1 and MCR-12.1 were separated in the same way within a clade containing ',False),('Cupriavidus',True),(' sequences, at 99.8 and 100 for MCR-5.1 and 58.5 and 93 for MCR-12.1. MCR-4.1 was sister to WP_220053229.1 of ',False),('Shewanella',True),(' at 100 and 100, MCR-9.1 to WP_261396260.1 of ',False),('C. freundii',True),(' at 98.9 and 100, MCR-10.1 to WP_232921000.1 of ',False),('Buttiauxella cochleicola',True),(' at 54.7 and 98. MCR-8.1 sat alone on a branch that resolves it against no particular chromosomal relative, at 84.8 SH-aLRT and 89 ultrafast bootstrap. Support for the placement of MCR-8.1, MCR-10.1 and MCR-12.1 is weaker than for the rest, so the position of these three within the clade should be treated as provisional even though their separation from the other mobilised proteins is not in question.',False)])
CON="A constrained maximum-likelihood tree forcing the eleven mobilised proteins into one clade reached a log-likelihood of {c:.2f} against {m:.2f} for the unconstrained tree, a difference of {d:.1f} units. The approximately unbiased test rejected the constrained topology at p = 8.1 x 10-6. The Kishino-Hasegawa and Shimodaira-Hasegawa tests and their weighted variants gave p < 0.001, and the expected likelihood weight of the constrained tree was 7.2 x 10-283. A single origin for the mobilised families can therefore be excluded, and the nine lineages recovered in the unconstrained tree represent at least nine separate transfers out of chromosomes and into mobile elements.".format(c=T['con_lnl'],m=T['ml_lnl'],d=T['deltaL'])
P(CON)

RICH([('The expanded analysis gave the same answer in a stronger form. With the 28 unclustered records added and the tree rooted on the superfamily outgroup, ten separate mobilised lineages were recovered rather than nine, because the chromosomal ',False),('Moraxella',True),(' protein A0A220T316 falls between MCR-1.1 and the MCR-2, MCR-6 pair. MCR-1.1 and that protein are sisters at 99.8 SH-aLRT and 100 ultrafast bootstrap, MCR-3.1 and A0ABX6NRT3 of ',False),('Aeromonas media',True),(' at 100 and 100, and MCR-2.1 and MCR-6.1 at 95.6 and 100. The four superfamily proteins used as outgroup did not themselves form a clade, so the root position is approximate and we treat the rooted analysis as a check on the primary one rather than as a replacement for it. In the same tree all 35 sequences annotated here as OpgE-like fall in a clade with OpgE at 93.9 SH-aLRT and 100 ultrafast bootstrap, a clade that also admits four CptA-like sequences; the tightest clade containing OpgE and no CptA-like sequence holds 29 of them at 99.9 and 100.',False)])
H('3.3. Each family has a distinct closest chromosomal relative',3)
RICH([('Identity to the nearest full-length chromosomal protein varied more than twofold across the families (Table 2), leaving aside for the moment the two records that are identical to MCR-5.1 and MCR-6.1. MCR-1.1 was 98.7% identical to A0A220T316 of ',False),('Moraxella',True),(' sp. MSG13C03, MCR-3.1 was 95.0% identical to A0ABX6NRT3 of ',False),('Aeromonas media',True),(', MCR-9.1 was 87.4% identical to WP_232921000.1 of ',False),('B. cochleicola',True),(' and MCR-10.1 84.6% to the same protein. MCR-6.1 reached 82.3% and MCR-2.1 81.0% against the ',False),('Moraxella',True),(' record, MCR-4.1 81.5% against A3D4D9 of ',False),('Shewanella baltica',True),(' OS155, and MCR-7.1 78.3% against WP_499669208.1 of ',False),('Aeromonas jandaei',True),('. Three families were much more isolated: MCR-5.1 at 45.1%, MCR-8.1 at 43.8% and MCR-12.1 at 40.6%.',False)])
RICH([('Two chromosomal records were identical to catalogued alleles over their entire length. A0A220T317 of ',False),('Moraxella',True),(' sp. MSG47C17 matches MCR-6.1 residue for residue, and A0A2R3NW71 of ',False),('Aeromonas hydrophila',True),(' matches MCR-5.1. Neither record is annotated as a resistance determinant. A chromosomal gene identical to a mobilised allele is the clearest evidence available that the two pools are continuous, and it also shows that the identity values above are lower bounds set by what has been sequenced rather than by what exists.',False)])
RICH([('Two cautions apply to this table. First, values computed against a clustered set understate the closeness of the relationship. In the clustered set MCR-1.1 reached only 62.4%, MCR-2.1 64.1%, MCR-3.1 66.9% and MCR-6.1 65.1%, so clustering had removed the true closest relative of five of the eleven families, in one case by 36 percentage points. Second, partial sequences inflate identity measured over the aligned region. The 400-residue WP_261396260.1 of ',False),('C. freundii',True),(' is 99.0% identical to MCR-9.1 over the part of the protein it covers, which is not comparable with a full-length value and is excluded here.',False)])
RICH([('The families were in most cases more distant from each other than from their chromosomal relatives. Identity between reference alleles ranged from 31.7% to 87.9% with a mean of 41.5% (Figure 2a). Three blocks stood out: MCR-1, MCR-2 and MCR-6 at 81.4% to 87.9%; MCR-3 and MCR-7 at 69.8%; MCR-9 and MCR-10 at 82.9%. Between the blocks, values fell to between 31.7% and 45%.',False)])

H('3.4. The catalytic apparatus was complete before mobilisation',3)
P('MCR-1.1 has a hydrophobic amino-terminal region ending near residue 183 and a periplasmic domain of about 358 residues (Figure 3a, 3b). In the mobilised proteins the predicted membrane-spanning segments numbered three to five and the periplasmic domain occupied between 357 and 382 residues. Across the chromosomal and related proteins the predicted segments ranged from one to five, with 163 of the 176 carrying three or more. Thirteen carry fewer. Only one of those is a short record, the 400-residue partial sequence discussed above; the others are of ordinary length, so the shortfall reflects the limits of a hydropathy heuristic rather than a different architecture.')
RICH([('Of the sixteen positions taken from the MCR-1 structures, six carry the same residue in every sequence in the dataset: Glu246, Thr285, His390, His395, Asp465 and His466 (Table 1). Their invariance is a property of the superfamily and carries no information about mobilisation, and we report it only to establish that no sequence in the dataset is a pseudogene product or a degraded fragment. The other ten vary. Measured against the residue in MCR-1.1 across the 176 chromosomal and related proteins of the expanded dataset, Asn329 differs in 93%, Ser284 in 72%, Cys356 and Cys364 in 49%, Lys333 in 48%, and Cys281, Cys291, Cys414, Cys422 and His478 in 29%. Table 1 reports occupancy in the 150 chromosomal proteins of the primary dataset, a different denominator and therefore a different set of percentages. Two of the ten, Ser284 and Asn329, also vary within the mobilised set, so the remaining eight are treated as the informative set throughout. Eighty-nine of the 176 proteins carry the MCR-1.1 residue at all eight.',False)])
P('Ancestral reconstruction was carried out on those ten positions at the stem node of each mobilised lineage, which is the last node that lineage shares with chromosomal sequences. All six cysteines, Lys333 and His478 were reconstructed with posterior probability 1.00 at all nine stem nodes. The two positions that vary within the mobilised set behaved differently and informatively. Ser284 and Asn329 were reconstructed as alanine and aspartate, the chromosomal configuration, at six of the nine nodes; as serine and asparagine at the node leading to MCR-1, MCR-2 and MCR-6; as alanine and asparagine at the node leading to MCR-12; and as asparagine and glutamine at the node leading to MCR-5, where the posterior probability at position 284 falls to 0.43. The reconstruction is therefore following real variation rather than returning the query sequence. Repeating the analysis on the outgroup-rooted topology of the expanded dataset returned the same residue in all 72 comparisons, eight informative positions across the nine lineages of the primary analysis, so the reconstruction at these positions does not depend on the position of the root.')

H('3.5. Synonymous sites are saturated between families',3)
SAT="Pairwise maximum-likelihood estimation across the fifteen-taxon between-family codon alignment gave dS above one for {a} of {b} comparisons. The median was 63.95 and the maximum {x:.1f}. Only three pairs fell below one, and all three were shallow comparisons: the two Moraxellaceae chromosomal proteins against each other at dS = 0.10 and omega = 0.054, MCR-6.1 against MCR-2.1 at dS = 0.50 and omega = 0.143, and MCR-9.1 against MCR-10.1 at dS = 0.98 and omega = 0.091. No estimate of the ratio between families is interpretable at this level of synonymous divergence, and none is reported.".format(a=S['n_dS_gt1'],b=S['n_pairs'],m=S['median_dS'],x=S['max_dS'])
P(SAT)
RICH([('Within families, where synonymous divergence is low, the one-ratio model gave values well below one in every case for which the ratio could be estimated (Table 3): 0.080 for ',False),('mcr-2',True),(', 0.135 for ',False),('mcr-3',True),(', 0.159 for ',False),('mcr-4',True),(', 0.167 for ',False),('mcr-8',True),(', 0.251 for ',False),('mcr-10',True),(' and 0.640 for ',False),('mcr-1',True),('. For ',False),('mcr-5',True),(' the synonymous tree length was zero and the ratio is undefined. The high value for ',False),('mcr-1',True),(' accompanies the lowest synonymous tree length of the set, 0.084, which is what a recently disseminated gene looks like rather than a gene under a different selective regime.',False)])
RICH([('Site models were fitted to ',False),('mcr-1',True),(', the family with the largest set of closely related alleles. The comparison of M1a with M2a gave 2 delta lnL = 8.64 and p = 0.013, while the more conservative comparison of M7 with M8 gave 2 delta lnL = 5.01 and p = 0.082. The seven positions flagged by the Bayes empirical Bayes procedure lie in or immediately after the amino-terminal membrane region, at residues 1, 2, 8, 13, 153, 187 and 189, and only two reach a posterior probability above 0.95. None is in the catalytic domain, which begins near residue 190. Given the low synonymous divergence within the family, the accuracy and power of site-level prediction are limited (Anisimova et al., 2002), and we draw no conclusion about adaptive change from this result.',False)])
RICH([('Base composition was markedly heterogeneous (Figure 5c). G+C content of the reference alleles ranged from 40.1% for ',False),('mcr-4',True),(' to 56.2% for ',False),('mcr-7',True),(', and third-position G+C from 37.5% for ',False),('mcr-8',True),(' to 76.9% for ',False),('mcr-7',True),('. Several families sit well away from the value of roughly 50% typical of ',False),('E. coli',True),(' and ',False),('Klebsiella pneumoniae',True),(', which is consistent with recent arrival from genomes of different composition.',False)])

H('3.6. Mobile elements flank the mobilised copies',3)
RICH([('Six loci carried annotation informative enough to describe the neighbourhood of the transferase gene (Figure 4). On pHNSHP45, ',False),('mcr-1',True),(' lies with an ISApl1 transposase inside a 3.7 kb element annotated as a composite transposon, downstream of the ',False),('nikAB',True),(' mobilisation genes. On pKP37-BE, ',False),('mcr-2',True),(' is flanked by proteins annotated as transposase and resolvase. The ',False),('mcr-5',True),(' deposit places the gene within a Tn3-family transposon. In the ',False),('mcr-4',True),(', ',False),('mcr-7.1',True),(' and ',False),('mcr-8',True),(' deposits the gene sits on a plasmid backbone among replication and transfer functions.',False)])
RICH([('The four chromosomal donor loci looked different. In ',False),('Faucicola osloensis',True),(' the transferase gene lies between a PAP2-family lipid A phosphatase and an Rhs-family protein, within a stretch of housekeeping genes that includes ',False),('glnD',True),(', ',False),('hemA',True),(', ',False),('lolB',True),(' and ',False),('tyrS',True),('. Across the four loci, 40 predicted open reading frames within about 10 kb either side of the transferase gene were searched against transposase profiles, and none scored above threshold. That window is narrower than the 30 to 50 kb used in dedicated studies of composite transposons, so the result establishes only that no transposase lies immediately beside these genes. It does not show that the loci are free of mobile elements, and it is not evidence that they are immobile.',False)])

H('3.7. Reference-based detection does not reach the chromosomal pool',3)
RICH([('Profiles were built for the eight families with at least three catalogued alleles, with the threshold for each set at the lowest score reached by one of its own alleles. Thresholds ranged from 1104.6 for ',False),('mcr-3',True),(' to 1338.7 for ',False),('mcr-8',True),('. Of the 178 chromosomal and related proteins screened, 175 returned a score and three reached a threshold: A0A220T316 of ',False),('Moraxella',True),(' sp. MSG13C03, which is 98.7% identical to MCR-1.1, and the two ',False),('Aeromonas',True),(' proteins A0ABX6NRT3 and A0A2R3NW71, which are 95.0% and 100% identical to MCR-3.1 and MCR-5.1. Detection therefore reaches the chromosomal pool only where a protein is at least 95% identical to an allele of a family that has enough catalogued members to model.',False)])

H('3.8. Candidates for prioritised follow-up',3)
RICH([('Ranking the chromosomal and related proteins by identity to the closest mobilised family gives a list of genes that would be worth examining first if the question is which gene might be mobilised next (Supplementary Table S1). Among full-length sequences, two proteins exceed 90% identity, six exceed 80% and eighteen exceed 60%, and the two records identical to MCR-5.1 and MCR-6.1 sit above all of them. The top of the list is occupied by the taxa already implicated. Moraxellaceae records occupy seven of the top twenty, ',False),('Aeromonas',True),(' six and ',False),('Shewanella',True),(' five. Below them sits a second tier of ',False),('Enterobacterales',True),(' at 50% to 60%: ',False),('Edwardsiella tarda',True),(' at 56.2% and ',False),('Hafnia alvei',True),(' at 55.5%, both closest to MCR-10.1.',False)])
P('This ranking is a similarity prior and nothing more. A gene becomes a reservoir when it is both close enough to function after transfer and situated where transfer can happen, and only the first of those can be assessed from a protein record. We were not able to examine the genomic context of most of the candidates, because they are held in the databases as protein records without an accessible assembly. The list should therefore be read as a set of targets for sequencing and context analysis, not as a set of established reservoirs. Two additional criteria that can be evaluated from the protein are given in the table: whether the complete informative active-site set is present, and whether the two-domain architecture is intact. Eighty-nine of the 176 proteins satisfy the first, and 163 the second.')

# ---------------- Discussion ----------------
H('4. Discussion')
RICH([('The mobilised families do not share an origin. They occupy the clade that also holds chromosomal EptA, but within it they sit among chromosomal sequences from taxa that are not closely related to one another, and a tree that forces them together is rejected by every test we applied. Nine lineages were recovered, which sets a floor rather than a count: families whose donors have not been sequenced will appear more isolated than they are, and two chromosomal records identical to catalogued alleles show how much of the relevant diversity is still undescribed. Moraxellaceae, ',False),('Shewanella',True),(', ',False),('Aeromonas',True),(', ',False),('Cupriavidus',True),(' and ',False),('Buttiauxella',True),(' each account for at least one event. The pattern is of a gene function repeatedly captured from whichever genome happened to be nearby, not of one ancestral resistance gene spreading.',False)])
P('The catalytic apparatus supports that reading directly. Six positions are occupied identically in every protein examined, mobilised or not, which tells us only that the superfamily constrains them. Eight of the ten positions that vary are informative about mobilisation, and at the stem node of every mobilised lineage all eight are reconstructed with a posterior probability of 1.00. The remaining two, Ser284 and Asn329, are reconstructed in the chromosomal configuration at six of the nine nodes, as serine and asparagine at the node leading to MCR-1, MCR-2 and MCR-6, and in two further configurations at the nodes leading to MCR-12 and MCR-5, which is what makes the result a finding rather than a restatement of the alignment. Nothing suggests that the transition from chromosome to plasmid required a change in the enzyme. What the donor already did, the mobilised gene continued to do.')
RICH([('Where the transition shows is in the flanking DNA. Three of the six informative deposits place a transposase or an insertion sequence within a few kilobases of the mobilised gene, and the other three place it on a plasmid backbone among replication and transfer functions. The ISApl1 arrangement around ',False),('mcr-1',True),(' is the clearest and is consistent with the transposition model proposed for Tn6330 (Snesrud et al., 2016, 2018; Poirel, Kieffer, and Nordmann, 2017). No transposase was found within about 10 kb of the four chromosomal loci we examined, but we draw no conclusion from that. Composite transposons are routinely identified using windows three to five times wider, and a negative result at 10 kb does not exclude an element at 25 kb. The comparison between mobilised and chromosomal contexts in this paper is therefore suggestive and not conclusive.',False)])
RICH([('The identity values distribute in a way that is informative about timing, once the artefacts are removed. MCR-1 differs from a chromosomal ',False),('Moraxella',True),(' protein by 1.3%, MCR-3 from a chromosomal ',False),('Aeromonas media',True),(' protein by 5.0%, and MCR-5 and MCR-6 have chromosomal counterparts that are identical to them. Those events are recent on any reading. MCR-9 and MCR-10 are 87.4% and 84.6% identical to their closest counterpart in ',False),('B. cochleicola',True),(', which places them further back. MCR-8 and MCR-12, at 43.8% and 40.6%, either come from lineages that have not been sampled or are older than the rest. A 400-residue partial protein of ',False),('C. freundii',True),(' is 99.0% identical to MCR-9.1 over the region it covers, but a value measured on a fragment is not comparable with one measured on a whole protein, and the recency of the ',False),('mcr-9',True),(' event should not be judged from it.',False)])
RICH([('The practical implication concerns surveillance, and it is now supported by a test rather than by assertion. A reference-based search using the most permissive threshold compatible with family boundaries reached three of the 178 chromosomal and related proteins, and all three were at least 95% identical to an allele of a well-catalogued family. Everything below that was missed, including a protein 87.4% identical to MCR-9.1. The sharpest case is A0A220T317 of ',False),('Moraxella',True),(' sp. MSG47C17, which is identical to MCR-6.1 residue for residue and was not detected, because ',False),('mcr-6',True),(' has two catalogued alleles and cannot be modelled as a family at all. Detection failure here is therefore not only a matter of divergence but of how unevenly the families are catalogued. A survey that asks which genomes carry a known ',False),('mcr',True),(' allele is unlikely to return a signal from a genome carrying a gene that a future family will be named after, and profile-based searching at the level of the family, rather than the allele, would narrow that gap at the cost of a specificity problem that would have to be managed.',False)])
RICH([('Just under a quarter of the chromosomal transferases in this dataset turned out to act on osmoregulated periplasmic glucans rather than on lipopolysaccharide. That distinction was not visible in the annotation of the records, which describe most of them simply as phosphoethanolamine transferases or sulfatase-family proteins, and it matters for anyone using annotation alone to estimate how many potential colistin resistance genes a genome carries. Counts made that way will be inflated. The ',False),('opgE',True),('-like proteins belong to the same superfamily and share the catalytic residues, but they have a different substrate and there is no evidence that any of them confers resistance.',False)])
P('Several limitations apply. Retrieval used one representative per cluster per genus, and although the identity analyses were repeated without clustering for the implicated donor genera, the wider dataset remains a sample rather than a census. The deep nodes of the tree are weakly supported, which is usual for a family this divergent, and the conclusion that mobilisation happened repeatedly rests on the topology test rather than on those nodes. Synonymous sites are saturated between families, so nothing can be said about the strength of selection during the transfer events themselves. Genomic context could be examined for only a small number of loci, and the window was narrow. Several of the sequences in the closest-relative table come from draft assemblies and metagenome-assembled genomes, where the distinction between a chromosomal and a plasmid location is not always reliable.')

H('5. Conclusions')
RICH([('Every ',False),('mcr',True),(' family with a catalogued reference allele falls within the clade that also holds chromosomal EptA, although support for that clade is modest, and the families entered the mobile gene pool on at least nine separate occasions rather than once, or ten when the dataset is expanded. A tree that forces them together is rejected decisively. The catalytic machinery was complete before mobilisation and has been maintained under purifying selection within every family for which the ratio could be estimated. What changed was the genomic setting. The chromosomal genes that now sit closest to the mobilised families are found in ',False),('Moraxella',True),(', ',False),('Faucicola',True),(', ',False),('Aeromonas',True),(', ',False),('Shewanella',True),(', ',False),('Buttiauxella',True),(' and ',False),('Cupriavidus',True),(', two of them identical to catalogued alleles. Reference-based surveillance reaches only the few that are at least 95% identical to an allele of a well-catalogued family, and misses the rest.',False)])

H('Author contributions')
P('[Initials] designed the study. [Initials] assembled the sequence datasets and performed the phylogenetic, structural and selection analyses. [Initials] carried out the genomic context and detection analyses. [Initials] drafted the manuscript. All authors reviewed and approved the final version.',indent=False)
H('Funding')
P('[Funding statement]',indent=False)
H('Conflict of interest')
P('The authors declare that the research was conducted in the absence of any commercial or financial relationships that could be construed as a potential conflict of interest.',indent=False)

# ---------------- References ----------------
doc.add_page_break()
H('References')
import re as _re
_old=open('/home/claude/pet/analysis/rev/doc/_oldrefs.txt').read()
refs=[x for x in _re.findall(r'"(.*?)",\n', _old+'\n', _re.S)]
DROP=('Price, M. N., Dehal','Piñeiro, C.','Nei, M., & Gojobori')
refs=[r for r in refs if not r.startswith(DROP)]
refs += [
"Anisimova, M., Bielawski, J. P., & Yang, Z. (2002). Accuracy and power of Bayes prediction of amino acid sites under positive selection. Molecular Biology and Evolution, 19(6), 950–958. https://doi.org/10.1093/oxfordjournals.molbev.a004152",
"Eddy, S. R. (2011). Accelerated profile HMM searches. PLoS Computational Biology, 7(10), e1002195. https://doi.org/10.1371/journal.pcbi.1002195",
"Guindon, S., Dufayard, J.-F., Lefort, V., Anisimova, M., Hordijk, W., & Gascuel, O. (2010). New algorithms and methods to estimate maximum-likelihood phylogenies: Assessing the performance of PhyML 3.0. Systematic Biology, 59(3), 307–321. https://doi.org/10.1093/sysbio/syq010",
"Hoang, D. T., Chernomor, O., von Haeseler, A., Minh, B. Q., & Vinh, L. S. (2018). UFBoot2: Improving the ultrafast bootstrap approximation. Molecular Biology and Evolution, 35(2), 518–522. https://doi.org/10.1093/molbev/msx281",
"Kalyaanamoorthy, S., Minh, B. Q., Wong, T. K. F., von Haeseler, A., & Jermiin, L. S. (2017). ModelFinder: Fast model selection for accurate phylogenetic estimates. Nature Methods, 14(6), 587–589. https://doi.org/10.1038/nmeth.4285",
"Minh, B. Q., Schmidt, H. A., Chernomor, O., Schrempf, D., Woodhams, M. D., von Haeseler, A., & Lanfear, R. (2020). IQ-TREE 2: New models and efficient methods for phylogenetic inference in the genomic era. Molecular Biology and Evolution, 37(5), 1530–1534. https://doi.org/10.1093/molbev/msaa015",
"Sbissi, I., Kammoun, I., El May, H., Bouzidi, T., Ghodhbane-Gtari, F., & Gtari, M. (2025). Reclassification of Moraxella boevrei, M. osloensis and M. atlantae into the genus Faucicola, and proposal of a new genus within the family Moraxellaceae, Lwoffella lincolnii gen. nov., comb. nov., to accommodate the divergent species Moraxella lincolnii. International Journal of Systematic and Evolutionary Microbiology, 75(6), 006820. https://doi.org/10.1099/ijsem.0.006820",
"Shimodaira, H. (2002). An approximately unbiased test of phylogenetic tree selection. Systematic Biology, 51(3), 492–508. https://doi.org/10.1080/10635150290069913",
"Tønjum, T., da Silva Franklin-Duarte, V., Berild, J. C., Gartzonika, K., Christaki, E., Mavromanolaki, V. E., … Boattini, M. (2026). Moraxella species isolated from blood cultures in Europe (MORAXEu): A multicentre study of epidemiology and antimicrobial susceptibility with complementary phylogenomic analysis of publicly available genomes. European Journal of Clinical Microbiology & Infectious Diseases. https://doi.org/10.1007/s10096-026-05640-z",
"UniProt Consortium. (2025). UniProt: The Universal Protein Knowledgebase in 2025. Nucleic Acids Research, 53(D1), D609–D617. https://doi.org/10.1093/nar/gkae1010",
"Xie, Z., & Tang, H. (2017). ISEScan: Automated identification of insertion sequence elements in prokaryotic genomes. Bioinformatics, 33(21), 3340–3347. https://doi.org/10.1093/bioinformatics/btx433",
"Yang, Z. (2007). PAML 4: Phylogenetic analysis by maximum likelihood. Molecular Biology and Evolution, 24(8), 1586–1591. https://doi.org/10.1093/molbev/msm088",
"Yang, Z., Nielsen, R., Goldman, N., & Pedersen, A.-M. K. (2000). Codon-substitution models for heterogeneous selection pressure at amino acid sites. Genetics, 155(1), 431–449. https://doi.org/10.1093/genetics/155.1.431",
]
for r in sorted(set(refs), key=lambda s: s.lower()):
    HANG(r)
print('references:',len(set(refs)))

# ---------------- Tables ----------------
doc.add_page_break()
H('Table 1')
P('Occupancy of the sixteen positions reported from the MCR-1 crystal structures. Positions follow MCR-1.1 numbering. The first six are invariant across the whole dataset and carry no information about mobilisation. Values give the most frequent residue and the percentage of sequences in each group that carry it. Counts are for the 161 sequences of the primary dataset; the percentages quoted in section 3.4 are for the 176 chromosomal and related proteins of the expanded dataset and are therefore not the complement of the values here.',indent=False)
import json as _json
sites=_json.load(open('/home/claude/pet/analysis/catalytic_sites.json'))
role={'E246':'metal coordination','T285':'catalytic nucleophile','H390':'metal coordination','H395':'metal coordination','D465':'metal coordination','H466':'metal coordination','H478':'active site','K333':'active site','N329':'active site','S284':'adjacent to nucleophile','C281':'disulfide 1','C291':'disulfide 1','C356':'disulfide 2','C364':'disulfide 2','C414':'disulfide 3','C422':'disulfide 3'}
order=['E246','T285','H390','H395','D465','H466','C281','C291','C356','C364','C414','C422','K333','H478','S284','N329']
byname={s['site']:s for s in sites}
rows=[['Position','Role','Mobilised MCR (n = 11)','EptA clade, chromosomal (n = 65)','All chromosomal (n = 150)']]
for k in order:
    s=byname[k]
    rows.append([k,role[k],'%s %.0f%%'%(s['mcr'],s['mcr_pct']),'%s %.0f%%'%(s['epta'],s['epta_pct']),'%s %.0f%%'%(s['chrom'],s['chrom_pct'])])
TABLE(rows)

doc.add_page_break()
H('Table 2')
P('Closest chromosomal relative of each mobilised family, computed over full-length sequences of the unclustered 191-sequence dataset. Values obtained against the clustered set are given for comparison. The partial protein WP_261396260.1 is excluded.',indent=False)
rows=[['Family','Closest full-length relative','Organism','Identity (%)','Identity in the clustered set (%)']]
tab2=[('MCR-1.1','A0A220T316','Moraxella sp. MSG13C03','98.7','62.4'),
 ('MCR-2.1','A0A220T316','Moraxella sp. MSG13C03','81.0','64.1'),
 ('MCR-3.1','A0ABX6NRT3','Aeromonas media','95.0','66.9'),
 ('MCR-4.1','A3D4D9','Shewanella baltica OS155','81.5','80.2'),
 ('MCR-5.1','WP_454751270.1','Cupriavidus sp.','45.1','45.1'),
 ('MCR-6.1','A0A220T316','Moraxella sp. MSG13C03','82.3','65.1'),
 ('MCR-7.1','WP_499669208.1','Aeromonas jandaei','78.3','78.3'),
 ('MCR-8.1','WP_280172752.1','Enterobacterales','43.8','47.5'),
 ('MCR-9.1','WP_232921000.1','Buttiauxella cochleicola','87.4','99.0'),
 ('MCR-10.1','WP_232921000.1','Buttiauxella cochleicola','84.6','84.6'),
 ('MCR-12.1','WP_507779059.1','Pseudomonas sp. RC25-4','40.6','41.0')]
for r in tab2: rows.append(list(r))
TABLE(rows)
P('Two chromosomal records are identical to catalogued alleles over their full length and are therefore not listed as closest relatives of their own family: A0A220T317 of Moraxella sp. MSG47C17 to MCR-6.1, and A0A2R3NW71 of Aeromonas hydrophila to MCR-5.1. Three values fall rather than rise when the search set is enlarged. For MCR-9.1 and MCR-8.1 the higher clustered value was obtained against the 400-residue partial protein WP_261396260.1, which is excluded here. For MCR-12.1 the difference of 0.4 percentage points reflects the realignment of a larger set and not a change of best hit.',indent=False,space_before=6)

doc.add_page_break()
H('Table 3')
P('Selection within each mobilised family, estimated by maximum likelihood under the one-ratio model on the catalogued allele set. Synonymous tree lengths are given so that the reader can judge whether the ratio is estimable.',indent=False)
wf=R['within_family']
rows=[['Family','Alleles','dN tree length','dS tree length','omega']]
for f in ['mcr-1','mcr-2','mcr-3','mcr-4','mcr-5','mcr-8','mcr-10']:
    v=wf[f]
    rows.append([f,v['n_alleles'],'%.4f'%v['dN_tree'],'%.4f'%v['dS_tree'],'not estimable' if v['omega'] is None else '%.3f'%v['omega']])
TABLE(rows)
P('Between families the estimator is unusable: synonymous divergence exceeded one substitution per site in 102 of the 105 pairwise comparisons, with a median of 63.95.',indent=False,space_before=6)

# ---------------- Figure legends ----------------
doc.add_page_break()
H('Figure legends')
P('Figure 1. Maximum-likelihood phylogeny of 161 phosphoethanolamine transferases inferred with IQ-TREE under LG+F+I+R6. Support is shown as SH-aLRT / ultrafast bootstrap from 1000 replicates each. Mobilised families are in bold. Chromosomal subtrees containing no mobilised protein are collapsed and labelled with the number of sequences they contain. The three paralogue groups are indicated on the right. Produced by 50_fig1.py.',indent=False)
P('Figure 2. (a) Pairwise amino acid identity between the reference alleles of the eleven mobilised families. (b) Identity of each family to its closest full-length chromosomal relative in the unclustered dataset, with the corresponding value from the clustered dataset shown behind it. Produced by 51_fig2.py.',indent=False,space_before=6)
P('Figure 3. (a) Kyte and Doolittle hydropathy of MCR-1.1 with the predicted membrane-spanning segments shaded and the sixteen structural positions marked; labels are staggered to avoid overlap. (b) Domain architecture of representative mobilised and chromosomal proteins drawn to scale. Produced by 53_fig3.py.',indent=False,space_before=6)
P('Figure 4. Genomic context of six mobilised deposits and of the chromosomal locus of Faucicola osloensis, drawn over a window of approximately 10 kb either side of the transferase gene. Gene labels alternate above and below the axis. Produced by 54_fig4.py.',indent=False,space_before=6)
P('Figure 5. (a) Distribution of synonymous divergence across the between-family comparisons, showing saturation. (b) Ratio of non-synonymous to synonymous change within each family against its synonymous tree length; labels are offset to avoid overlap. (c) Overall and third-position G+C content of the reference alleles. Produced by 52_fig5.py.',indent=False,space_before=6)

import italics as _it
_it.apply(doc)
doc.save('/mnt/user-data/outputs/Manuscript_revised.docx')
print('saved manuscript')
