# -*- coding: utf-8 -*-
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.enum.section import WD_SECTION
from docx.oxml.ns import qn
import json

doc=Document()
st=doc.styles['Normal']
st.font.name='Times New Roman'; st.font.size=Pt(12)
st.element.rPr.rFonts.set(qn('w:eastAsia'),'Times New Roman')
pf=st.paragraph_format
pf.line_spacing_rule=WD_LINE_SPACING.DOUBLE
pf.space_after=Pt(0)
for s in doc.sections:
    s.left_margin=s.right_margin=Inches(1.0); s.top_margin=s.bottom_margin=Inches(1.0)

def P(text='',style=None,align=None,italic=False,bold=False,indent=True,space_before=0,size=None):
    p=doc.add_paragraph()
    p.paragraph_format.line_spacing_rule=WD_LINE_SPACING.DOUBLE
    p.paragraph_format.space_before=Pt(space_before)
    p.paragraph_format.space_after=Pt(0)
    if indent: p.paragraph_format.first_line_indent=Inches(0.5)
    if align: p.alignment=align
    r=p.add_run(text); r.italic=italic; r.bold=bold
    if size: r.font.size=Pt(size)
    return p

def RICH(parts, align=None, indent=True, space_before=0):
    p=doc.add_paragraph()
    p.paragraph_format.line_spacing_rule=WD_LINE_SPACING.DOUBLE
    p.paragraph_format.space_before=Pt(space_before)
    p.paragraph_format.space_after=Pt(0)
    if indent: p.paragraph_format.first_line_indent=Inches(0.5)
    if align: p.alignment=align
    for t,it in parts:
        r=p.add_run(t); r.italic=it
    return p

def H(text,level=1):
    p=doc.add_paragraph()
    p.paragraph_format.line_spacing_rule=WD_LINE_SPACING.DOUBLE
    p.paragraph_format.space_before=Pt(12); p.paragraph_format.space_after=Pt(0)
    r=p.add_run(text); r.bold=True; r.font.size=Pt(12 if level>1 else 12)
    if level>2: r.bold=False; r.italic=True
    return p

def HANG(text):
    p=doc.add_paragraph()
    p.paragraph_format.line_spacing_rule=WD_LINE_SPACING.DOUBLE
    p.paragraph_format.space_after=Pt(0)
    p.paragraph_format.left_indent=Inches(0.5)
    p.paragraph_format.first_line_indent=Inches(-0.5)
    p.add_run(text)
    return p

# ---------------- Title page ----------------
t=doc.add_paragraph(); t.alignment=WD_ALIGN_PARAGRAPH.CENTER
t.paragraph_format.line_spacing_rule=WD_LINE_SPACING.DOUBLE
r=t.add_run('Chromosomal phosphoethanolamine transferases as evolutionary sources and standing reservoirs of mobilised colistin resistance in Enterobacterales')
r.bold=True

P('',indent=False)
P('Running title: Chromosomal origins of mcr genes',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
P('',indent=False)
P('Author names and affiliations',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False,bold=True)
P('[Author 1]1*, [Author 2]1, [Author 3]2',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
P('1 [Department], [Institution], [City], [Country]',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
P('2 [Department], [Institution], [City], [Country]',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
P('* Correspondence: [email]',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False)
doc.add_page_break()

# ---------------- Abstract ----------------
H('Abstract')
P('The ten families of mobilised colistin resistance (mcr) genes encode phosphoethanolamine transferases that are structurally and functionally equivalent to chromosomal EptA. Where each family came from, and which chromosomal genes might be recruited next, remain only partly resolved. We assembled 150 chromosomal phosphoethanolamine transferases from RefSeq, drawn from 44 genus-level lineages of Enterobacterales and from candidate donor taxa outside the order, and analysed them together with reference alleles of MCR-1 to MCR-10 and MCR-12. Maximum-likelihood phylogeny under the LG model placed every mobilised protein inside a single clade of 76 sequences that also contains chromosomal EptA of Escherichia coli, while the paralogous EptB and CptA/EptC clades were recovered as separate, well-supported groups. The mobilised proteins were not monophyletic within that clade. Each family instead grouped with a different chromosomal relative, and the identity to the closest chromosomal protein ranged from 41.0% for MCR-12 to 99.0% for MCR-9. The catalytic threonine, the metal-coordinating glutamate, histidine and aspartate residues and the three disulfide-forming cysteine pairs were invariant across all 161 proteins, and marginal ancestral reconstruction recovered the complete catalytic set at every node subtending a mobilised family, with posterior probabilities of 1.00. Codon-based estimates gave dN/dS values of 0.08 to 0.35 between families and 0.10 to 0.32 between each mobilised gene and its chromosomal progenitor. Insertion sequences or transposases flanked the mobilised copies in five of the six loci with informative annotation, whereas no transposase profile was detected within 9 kb of four chromosomal donor genes. Eight chromosomal proteins shared at least 60% identity with a mobilised family, and these, together with the wider EptA clade in Aeromonas, Shewanella, Buttiauxella, Vibrio and Moraxellaceae, constitute the most plausible source of further mobilisation events.',indent=False)
P('',indent=False)
RICH([('Keywords: ',False),('mcr',True),(', colistin resistance, phosphoethanolamine transferase, ',False),('eptA',True),(', comparative genomics, horizontal gene transfer, One Health',False)],indent=False)
doc.add_page_break()

# ---------------- Introduction ----------------
H('1. Introduction')
RICH([('Colistin returned to clinical use because there was little else left. Decades after it had been abandoned on grounds of nephrotoxicity, the spread of carbapenem-resistant ',False),('Enterobacterales',True),(' forced clinicians back onto polymyxins for infections that no longer responded to anything else (Poirel et al., 2017). Resistance to colistin was, for a long time, thought to arise only through chromosomal mutation, most often in the two-component regulators that control lipid A modification. That assumption ended with the description of ',False),('mcr-1',True),(' on a conjugative plasmid from a Chinese pig isolate (Liu et al., 2016). Within three years, nine further families had been reported from humans, food animals and the environment on four continents, and the gene is now a standing feature of surveillance programmes worldwide.',False)])
RICH([('All ',False),('mcr',True),(' products belong to the alkaline phosphatase superfamily and act as phosphoethanolamine transferases. They attach a phosphoethanolamine group to the 1 and 4′ phosphates of lipid A, which lowers the net negative charge of the outer membrane and weakens the electrostatic attraction that polymyxins depend on. The same chemistry is performed by chromosomal enzymes that long predate the clinical use of colistin. ',False),('Escherichia coli',True),(' carries three of them. EptA modifies lipid A under PmrAB control, EptB transfers phosphoethanolamine to the outer Kdo residue of the inner core (Reynolds et al., 2005), and CptA, also called EptC, modifies the heptose I phosphate. ',False),('Neisseria meningitidis',True),(' LptA and ',False),('Campylobacter jejuni',True),(' EptC perform related reactions and contribute to intrinsic resistance against cationic antimicrobial peptides (Tzeng et al., 2005; Cullen et al., 2011; Wanty et al., 2013).',False)])
RICH([('Structural work on MCR-1 showed how close that relationship is. The periplasmic domain adopts the alkaline phosphatase fold, binds zinc, and uses a threonine nucleophile that becomes transiently phosphorylated during catalysis (Hu et al., 2016; Ma et al., 2016; Coates et al., 2017). The same fold, the same metal site and the same nucleophile are present in ',False),('N. meningitidis',True),(' LptA, whose structure was solved years before ',False),('mcr-1',True),(' was found (Wanty et al., 2013). Mobilisation therefore did not require a new enzyme. It required a route out of a chromosome, and insertion sequences supplied it. ISApl1 brackets ',False),('mcr-1',True),(' in a composite transposon designated Tn6330, and the element is progressively lost once the gene has settled on a stable plasmid backbone (Snesrud et al., 2016; Poirel et al., 2017; Snesrud et al., 2018).',False)])
RICH([('Individual donor taxa have been proposed for several families. ',False),('Moraxella',True),(' species carry chromosomal genes that resemble ',False),('mcr-1',True),(' and ',False),('mcr-2',True),(' closely enough to be regarded as their probable origin (AbuOun et al., 2017; Kieffer et al., 2017), and ',False),('mcr-4',True),(' was noted on discovery to resemble a chromosomal protein of ',False),('Shewanella frigidimarina',True),(' (Carattoli et al., 2017). These observations were made family by family, using whatever comparisons were available at the time. What has not been done is to place all ten families in one phylogeny with a taxonomically balanced set of chromosomal homologues, and then ask, with the same evidence, three questions in sequence. Do the mobilised genes share a single origin or many? Which chromosomal lineage sits closest to each of them? And which chromosomal genes have the properties that would make them plausible candidates for the next mobilisation event?',False)])
RICH([('This study addresses those questions. Chromosomal phosphoethanolamine transferases were retrieved across the breadth of the ',False),('Enterobacterales',True),(' and from the taxa implicated as donors, analysed together with the reference alleles of every named ',False),('mcr',True),(' family, and examined for phylogenetic placement, domain architecture, active-site conservation, ancestral state, selective regime, base composition and genomic context.',False)])

# ---------------- Methods ----------------
H('2. Materials and Methods')
H('2.1. Reference alleles of mobilised colistin resistance genes',3)
RICH([('Nucleotide sequences for the reference allele of each ',False),('mcr',True),(' family were taken from the NCBI Bacterial Antimicrobial Resistance Reference Gene Catalog (Feldgarden et al., 2021), as distributed with ABRicate v1.0.1 (https://github.com/tseemann/abricate). The catalogue provided ',False),('mcr-1.1',True),(' (NG_050417.1), ',False),('mcr-2.1',True),(' (NG_051171.1), ',False),('mcr-3.1',True),(' (NG_055505.1), ',False),('mcr-4.1',True),(' (NG_057470.1), ',False),('mcr-5.1',True),(' (NG_055658.1), ',False),('mcr-6.1',True),(' (NG_055781.1), ',False),('mcr-7.1',True),(' (NG_056413.1), ',False),('mcr-8.1',True),(' (NG_061399.1), ',False),('mcr-10.1',True),(' (NG_066767.1) and ',False),('mcr-12.1',True),(' (NG_245195.1). The ',False),('mcr-9.1',True),(' allele (MK070339) was taken from the ResFinder database distributed with the same package. All 116 catalogued ',False),('mcr',True),(' alleles were retained for the analysis of base composition. Coding sequences were translated with the bacterial genetic code in Biopython v1.88 (Cock et al., 2009); every reference allele yielded a single open reading frame with one terminal stop codon and no internal stop.',False)])
H('2.2. Chromosomal phosphoethanolamine transferases',3)
RICH([('Candidate chromosomal homologues were retrieved from the NCBI RefSeq non-redundant protein collection (O’Leary et al., 2016) through the Entrez programming interface. For each of 35 genus-level taxa of ',False),('Enterobacterales',True),(' and for ten taxa outside the order that have been implicated as donors or that carry well-characterised paralogues (',False),('Moraxella',True),(', ',False),('Aeromonas',True),(', ',False),('Shewanella',True),(', ',False),('Vibrio',True),(', ',False),('Acinetobacter',True),(', ',False),('Neisseria',True),(', ',False),('Campylobacter',True),(', ',False),('Cupriavidus',True),(', ',False),('Pseudomonas',True),(' and ',False),('Burkholderia',True),('), proteins annotated as phosphoethanolamine transferases or as ',False),('eptA',True),(', ',False),('eptB',True),(', ',False),('eptC',True),(' or ',False),('cptA',True),(' gene products and between 400 and 700 residues in length were collected. The EptA, EptB and EptC proteins of ',False),('E. coli',True),(' K-12 MG1655 (NP_418538.2, NP_418002.2 and NP_418390.1) were added as anchors. The 353 retrieved proteins were dereplicated by greedy clustering on shared 4-mers at a Jaccard threshold of 0.5, which corresponds to approximately 80% identity, and one representative per cluster was retained; additional representatives were kept for the donor genera. The final working set contained 150 chromosomal proteins and 11 mobilised proteins, 161 in total. Accessions, organisms and lengths are listed in Supplementary Table S1.',False)])
H('2.3. Alignment and phylogenetic inference',3)
P('Protein sequences were aligned with FAMSA (Deorowicz et al., 2016) as implemented in pyfamsa v0.7.0, giving an alignment of 808 columns. Poorly aligned positions were removed with trimAl (Capella-Gutiérrez et al., 2009) in pytrimal v0.8.5 under the automated1 heuristic, leaving 313 columns. A maximum-likelihood tree was inferred from the trimmed alignment with VeryFastTree v4.0.4 (Piñeiro et al., 2020), a vectorised implementation of FastTree 2 (Price et al., 2010), under the LG substitution model (Le & Gascuel, 2008) with the CAT approximation and subsequent Gamma20 rescaling; the fitted shape parameter was 1.385. Branch support was estimated from 100 non-parametric bootstrap replicates generated by resampling alignment columns, each analysed under the same model, and bipartition frequencies were mapped onto the maximum-likelihood topology with DendroPy v5.1.0. The tree was rooted at its midpoint. Clades were delimited by expanding outward from each of the three E. coli anchors until a node was reached that contained another anchor.',indent=False)
H('2.4. Sequence identity, domain architecture and active-site mapping',3)
P('Pairwise amino acid identity was calculated over columns at which both sequences carried a residue in the untrimmed alignment. Hydropathy was computed on the Kyte and Doolittle scale over a sliding window of 19 residues, and contiguous segments of at least 17 residues with a mean value above 1.6 were merged and counted as predicted membrane-spanning segments. Residues reported from the MCR-1 crystal structures as catalytic, metal-coordinating or disulfide-forming (Hu et al., 2016; Ma et al., 2016; Coates et al., 2017; Zhao et al., 2018) were located in MCR-1.1, mapped to alignment columns, and their occupancy was tabulated separately for the mobilised proteins, for the chromosomal members of the EptA clade and for the full chromosomal set. Positional conservation was summarised as one minus the Shannon entropy of each column normalised by log2(20), computed only for columns with residues in at least 40% of the sequences of a group.',indent=False)
H('2.5. Ancestral sequence reconstruction',3)
P('Marginal ancestral states were reconstructed on the untrimmed alignment under the LG model with empirical equilibrium frequencies and four discrete gamma rate categories with a shape parameter of 1.385, using the rooted maximum-likelihood topology and its branch lengths. Conditional likelihoods were obtained by Felsenstein pruning, combined with the complementary likelihoods of the rest of the tree, and averaged over rate categories weighted by the per-site likelihood of each category. Exchangeabilities and equilibrium frequencies for the LG matrix were taken from the pyvolve v1.1.0 distribution. Nodes subtending each mobilised family and its closest chromosomal relatives were selected for reporting.',indent=False)
H('2.6. Selection and base composition',3)
RICH([('Codon alignments were generated by threading the coding sequences onto the corresponding protein alignments. Numbers of synonymous and non-synonymous substitutions per site were estimated by the counting method of Nei and Gojobori (1986) as implemented in Biopython. Pairs for which the estimator did not converge, which occurs when synonymous divergence is saturated, were excluded and are reported as such. Comparisons were made between the reference alleles of different ',False),('mcr',True),(' families and between each mobilised gene and the coding sequence of its closest chromosomal relative. G+C content was computed over whole coding sequences and at third codon positions.',False)])
H('2.7. Genomic context and detection of mobile elements',3)
RICH([('Genomic context was examined for the original deposits of ',False),('mcr-1',True),(' (KP347127), ',False),('mcr-2',True),(' (LT598652), ',False),('mcr-3',True),(' (KY924928), ',False),('mcr-4',True),(' (MF543359), ',False),('mcr-5',True),(' (KY807921), ',False),('mcr-7.1',True),(' (MG267386) and ',False),('mcr-8',True),(' (MG736312), and for the chromosomal donor loci. Annotated flat files and sequence were retrieved from the European Nucleotide Archive, and coding features within 8 to 9 kb of the transferase gene were extracted. For chromosomal loci without deposited annotation, open reading frames of at least 120 codons were predicted in all six frames within 9 kb of the gene and searched against the 266 transposase profile hidden Markov models distributed with ISEScan (https://github.com/xiezhq/ISEScan) using pyhmmer v0.12.3 at an E-value threshold of 1 × 10⁻⁵.',False)])
H('2.8. Data and code availability',3)
P('All sequences analysed are public records held by NCBI and the European Nucleotide Archive and are identified by accession in Supplementary Table S1. Alignments, the maximum-likelihood tree with bootstrap support, bootstrap replicate trees, reconstructed ancestral states and the analysis scripts accompany this article as supplementary files.',indent=False)

# ---------------- Results ----------------
H('3. Results')
H('3.1. A single clade contains chromosomal EptA and all mobilised families',3)
RICH([('The 161 proteins resolved into three groups that correspond to the three ',False),('E. coli',True),(' paralogues (Figure 1). The clade anchored by EptA contained 76 sequences, of which 65 were chromosomal and 11 were mobilised. The clade anchored by EptB contained 36 sequences and the clade anchored by CptA/EptC contained 49. No sequence fell outside these three groups. Chromosomal members of the EptA clade came from 44 genus-level lineages, among them ',False),('Escherichia',True),(', ',False),('Salmonella',True),(', ',False),('Klebsiella',True),(', ',False),('Citrobacter',True),(', ',False),('Enterobacter',True),(', ',False),('Serratia',True),(', ',False),('Yersinia',True),(', ',False),('Pectobacterium',True),(' and ',False),('Dickeya',True),(', together with ',False),('Aeromonas',True),(', ',False),('Shewanella',True),(', ',False),('Vibrio',True),(', ',False),('Plesiomonas',True),(', ',False),('Moraxella',True),(', ',False),('Cupriavidus',True),(', ',False),('Pseudomonas',True),(', ',False),('Burkholderia',True),(', ',False),('Neisseria',True),(' and ',False),('Campylobacter',True),('.',False)])
RICH([('Within that clade the mobilised proteins were dispersed rather than clustered. The smallest group containing all 11 of them also contained 63 chromosomal proteins and received only 28% bootstrap support, which is what would be expected if the families entered the mobile gene pool independently. Several small groupings were, by contrast, strongly supported. MCR-1.1, MCR-2.1 and MCR-6.1 formed a group with the ',False),('Faucicola osloensis',True),(' protein WP_490288700.1 and the ',False),('Moraxellaceae',True),(' protein WP_284034866.1 at 100% bootstrap support. MCR-9.1 grouped with the ',False),('Citrobacter freundii',True),(' protein WP_261396260.1 at 100% support, and MCR-10.1 joined that pair together with ',False),('Buttiauxella cochleicola',True),(' WP_232921000.1. MCR-5.1 grouped with two ',False),('Cupriavidus',True),(' proteins at 100% support. MCR-3.1 and MCR-7.1 fell among the ',False),('Aeromonas',True),(', ',False),('Buttiauxella',True),(' and ',False),('Citrobacter',True),(' sequences, and MCR-4.1 grouped with ',False),('Shewanella',True),('.',False)])
H('3.2. Each family has a distinct closest chromosomal relative',3)
RICH([('Identity to the nearest chromosomal protein varied more than twofold across the families (Figure 2b). MCR-9.1 was 99.0% identical to WP_261396260.1 of ',False),('C. freundii',True),(', a 400-residue partial protein that is most plausibly an ',False),('mcr-9',True),('-like gene resident in that genome. MCR-10.1 was 84.6% identical to WP_232921000.1 of ',False),('B. cochleicola',True),(', MCR-4.1 was 80.2% identical to WP_220053229.1 of ',False),('Shewanella',True),(' sp., and MCR-7.1 was 78.3% identical to WP_499669208.1 of ',False),('Aeromonas jandaei',True),('. The three Moraxellaceae-associated families sat lower, at 62.4% for MCR-1.1, 64.1% for MCR-2.1 and 65.1% for MCR-6.1 against ',False),('F. osloensis',True),(' WP_490288700.1. MCR-3.1 reached 66.9% against the ',False),('C. freundii',True),(' protein and 65.9% against ',False),('B. cochleicola',True),('. At the other end of the range, MCR-8.1 reached only 47.9%, MCR-5.1 45.1% against ',False),('Cupriavidus',True),(' and MCR-12.1 41.0% against a ',False),('Pseudomonas',True),(' protein.',False)])
RICH([('The families were, in most cases, more distant from each other than from their chromosomal relatives. Pairwise identity between reference alleles ranged from 31.1% to 87.9%, with a mean of 41.7% (Figure 2a). Three blocks stood out. MCR-1, MCR-2 and MCR-6 shared 81.4% to 87.9% identity; MCR-3 and MCR-7 shared 69.8%; MCR-9 and MCR-10 shared 82.9%. Across the blocks, values fell to between 31% and 46%. Identity to ',False),('E. coli',True),(' EptA ranged from 33.1% for MCR-1.1 to 41.8% for MCR-8.1, so no family is a recent derivative of the ',False),('E. coli',True),(' chromosomal gene.',False)])
H('3.3. The catalytic apparatus is invariant and older than mobilisation',3)
P('MCR-1.1 has a hydrophobic amino-terminal region that ends near residue 183 and a periplasmic domain of about 358 residues (Figure 3a, 3b). Across the whole dataset the predicted membrane-spanning segments numbered three to five and the periplasmic domain occupied between 357 and 382 residues in the mobilised proteins, so the two-domain architecture is uniform.',indent=False)
P('Sixteen positions reported from the MCR-1 structures were examined (Table 1). Glu246, Thr285, His390, His395, Asp465 and His466 were occupied by the same residue in all 11 mobilised proteins and in all 150 chromosomal proteins. Lys333 and His478 were invariant in the mobilised set and in the chromosomal members of the EptA clade but fell to 45% and 69% occupancy across the full chromosomal set, which includes the EptB and CptA/EptC paralogues. The six cysteines that form the three disulfide bonds behaved in the same way. Cys281, Cys291, Cys356, Cys364, Cys414 and Cys422 were present in every mobilised protein and in every chromosomal member of the EptA clade, and dropped to between 43% and 67% elsewhere. Conservation profiles (Figure 3c) show the pattern directly. The periplasmic domain is more conserved than the membrane anchor in all four groups, and the peaks coincide with the catalytic positions.',indent=False)
H('3.4. Ancestral reconstruction places the catalytic set before mobilisation',3)
P('Marginal reconstruction recovered the full catalytic set at every node subtending a mobilised family. At the node joining MCR-1, MCR-2 and MCR-6 to the Moraxellaceae proteins, Glu246, Cys281, Thr285, Cys291, Lys333, Cys356, Cys364, His390, His395, Cys414, Cys422, Asp465, His466 and His478 were all reconstructed with posterior probabilities of 1.00. The same was true at the nodes subtending MCR-3 with MCR-7, MCR-9 with MCR-10, MCR-4 with Shewanella and MCR-5 with Cupriavidus, and at the ancestor of the whole EptA clade. Mean marginal posterior probability across 808 alignment columns ranged from 0.61 at the Cupriavidus node to 0.74 at the mcr-9 and mcr-10 node. MCR-1.1 differs from the reconstructed pre-mobilisation ancestor at 109 of its 541 positions, a divergence of 20.1%, none of which falls at a catalytic residue.',indent=False)
H('3.5. Purifying selection and heterogeneous base composition',3)
RICH([('Codon-based comparisons between families gave dN/dS values of 0.081 to 0.351, with a median of 0.224 across the 12 pairs for which the estimator converged (Figure 5a). Comparisons between each mobilised gene and its chromosomal progenitor gave a similar range. Values were 0.164 for ',False),('mcr-2',True),(' and 0.100 for ',False),('mcr-6',True),(' against the ',False),('F. osloensis',True),(' gene, 0.114, 0.159 and 0.126 for ',False),('mcr-1',True),(', ',False),('mcr-2',True),(' and ',False),('mcr-6',True),(' against the ',False),('Moraxella',True),(' sp. gene, and 0.324 for ',False),('mcr-12',True),(' against the ',False),('Pseudomonas',True),(' gene (Figure 5b). The comparisons for ',False),('mcr-1',True),(' against ',False),('F. osloensis',True),(' and for ',False),('mcr-4',True),(' against ',False),('Shewanella',True),(' were saturated at synonymous sites and are not reported as ratios. Purifying selection is therefore the dominant regime both within the mobilised pool and between the mobilised genes and their chromosomal counterparts.',False)])
RICH([('Base composition was markedly heterogeneous (Figure 5c). G+C content of the reference alleles ranged from 40.1% for ',False),('mcr-4',True),(' to 58.3% for ',False),('mcr-12',True),(', and third-position G+C from 37.5% for ',False),('mcr-8',True),(' to 76.9% for ',False),('mcr-7',True),('. Several families sit well away from the value of roughly 50% typical of ',False),('E. coli',True),(' and ',False),('Klebsiella',True),(' chromosomes. The donor loci were themselves compositionally distinct, at 45.1% for ',False),('F. osloensis',True),(', 46.1% for ',False),('Moraxella',True),(' sp., 46.4% for ',False),('Shewanella',True),(' sp. and 57.7% for ',False),('Pseudomonas',True),(' sp.',False)])
H('3.6. Mobile elements flank the mobilised copies but not the chromosomal genes',3)
RICH([('Six loci carried annotation informative enough to describe the neighbourhood of the transferase gene (Figure 4). On pHNSHP45, ',False),('mcr-1',True),(' lies with an ISApl1 transposase inside a 3.7 kb element annotated as a composite transposon, downstream of the ',False),('nikAB',True),(' mobilisation genes. On pKP37-BE, ',False),('mcr-2',True),(' is flanked on both sides by proteins annotated as mobile element proteins. On pMCR4.3 a ',False),('tnpA',True),(' gene lies immediately downstream of ',False),('mcr-4',True),('. The ',False),('mcr-5',True),(' deposit carries ',False),('tnpR',True),(' and a 3.0 kb Tn3-family ',False),('tnpA',True),(' downstream of the transferase and an IS5/IS1182 transposase at the far end of the contig. On pKP91, ',False),('mcr-8',True),(' lies 4 kb from a DDE-family transposase. The ',False),('mcr-7.1',True),(' deposit was the exception, with mobilisation genes ',False),('mobC',True),(' and ',False),('mbeA',True),(' present but no transposase within 8 kb.',False)])
RICH([('The chromosomal picture was different. In ',False),('F. osloensis',True),(' the transferase gene lies between a PAP2-family lipid A phosphatase and an Rhs-family protein, within a stretch of housekeeping genes that includes ',False),('glnD',True),(', ',False),('hemA',True),(', ',False),('lolB',True),(' and ',False),('tyrS',True),('. Across the four donor loci examined, 40 predicted open reading frames within 9 kb of the transferase gene returned no significant match to any of 266 transposase profiles. Two neighbours are worth noting. The ',False),('mcr-7.1',True),(' plasmid carries ',False),('dgkA',True),(' and a PAP2-family gene immediately downstream of the transferase, and ',False),('mcr-8',True),(' is followed by ',False),('copR',True),(', ',False),('baeS',True),(' and ',False),('dgkA',True),('. Both arrangements echo chromosomal neighbourhoods and suggest that mobilisation captured flanking host sequence along with the transferase gene.',False)])
H('3.7. Candidate chromosomal reservoirs',3)
RICH([('Ranking the 150 chromosomal proteins by their identity to the closest mobilised family gives a short list of plausible sources for further mobilisation (Supplementary Table S1). Eight proteins reached at least 60% identity and five reached at least 70%. The top of the list is occupied by the taxa already implicated, namely ',False),('C. freundii',True),(' at 99.0%, ',False),('B. cochleicola',True),(' at 87.4%, ',False),('Shewanella',True),(' sp. at 80.2% and three ',False),('Aeromonas',True),(' species between 67.1% and 78.3%, followed by ',False),('F. osloensis',True),(' at 65.1% and a second Moraxellaceae protein at 64.5%. Below that threshold sits a broad second tier between 50% and 57% that has not so far been associated with mobilisation, comprising ',False),('Edwardsiella tarda',True),(', ',False),('Hafnia alvei',True),(', ',False),('Ewingella',True),(' sp., ',False),('Rahnella perminowiae',True),(', ',False),('Plesiomonas shigelloides',True),(' and four ',False),('Vibrio',True),(' species including ',False),('V. cholerae',True),('. The median chromosomal member of the EptA clade shares 42.8% identity with its closest mobilised family, so the second tier is well above the background of the clade.',False)])

# ---------------- Discussion ----------------
H('4. Discussion')
RICH([('The ten ',False),('mcr',True),(' families do not share a single origin. They occupy one clade, the clade that also contains chromosomal EptA, but within it they are scattered among chromosomal sequences from taxa that are not closely related to one another. Moraxellaceae, ',False),('Shewanella',True),(', ',False),('Aeromonas',True),(', ',False),('Cupriavidus',True),(', ',False),('Buttiauxella',True),(' and ',False),('Citrobacter',True),(' each sit closest to a different family. The simplest reading is that at least seven separate capture events moved a chromosomal gene onto a mobile element, and that the genes so captured were already competent phosphoethanolamine transferases when they left.',False)])
P('The invariance of the catalytic set supports that reading directly. Glu246, Thr285, the histidine pair at 390 and 395, Asp465 and His466 are occupied identically in every protein examined, mobilised or not, and ancestral reconstruction recovers all of them at every node subtending a mobilised family with maximum posterior probability. Nothing in the data suggests that the transition from chromosome to plasmid involved a change in the active site. The three disulfide bonds tell a slightly different story. They are invariant within the EptA clade and only sporadically present in the EptB and CptA/EptC paralogues, which marks them as a feature of this particular lineage rather than of the superfamily.',indent=False)
RICH([('Where the transition does show is in the flanking DNA. Five of the six informative deposits place a transposase or an insertion sequence within a few kilobases of the mobilised gene, the ISApl1 arrangement around ',False),('mcr-1',True),(' being the clearest case and consistent with the transposition model proposed for Tn6330 (Snesrud et al., 2016, 2018; Poirel et al., 2017). The chromosomal donor loci show no such elements. Four regions of 18 kb each, screened against 266 transposase profiles, returned nothing. The chromosomal genes sit among housekeeping functions, which is where one would expect a gene that has been part of the core lipid A modification machinery for a long time. Mobility is a property of the context, not of the gene.',False)])
RICH([('The identity values distribute in a way that is informative about timing. MCR-9 and its ',False),('C. freundii',True),(' counterpart differ by a single per cent, and MCR-10 and MCR-4 are within 15 to 20 per cent of their nearest chromosomal relatives. Those events look recent. The Moraxellaceae-associated families sit at 62% to 65%, which is close enough to identify the donor lineage with confidence but far enough to indicate that the sampled chromosomal genes are relatives of the true progenitor rather than the progenitor itself. MCR-5, MCR-8 and MCR-12, at 41% to 48%, are either older or drawn from lineages that remain unsampled. The compositional data point the same way. Third-position G+C ranges from 37.5% to 76.9% across the families, which is a wide spread for genes now resident in hosts with genomes near 50% G+C, and it indicates that amelioration after transfer has been incomplete.',False)])
RICH([('The practical implication concerns surveillance. Genomic surveillance for colistin resistance is built around the ten named families, and a gene that is 50% identical to any of them would not be flagged by the reference-based tools in routine use. The second tier identified here, ',False),('Edwardsiella',True),(', ',False),('Hafnia',True),(', ',False),('Ewingella',True),(', ',False),('Rahnella',True),(', ',False),('Plesiomonas',True),(' and ',False),('Vibrio',True),(', contains organisms that share aquatic and food-production environments with the taxa that have already contributed. ',False),('Aeromonas',True),(' and ',False),('Shewanella',True),(' were once in the same position, unremarkable environmental genera carrying a chromosomal gene of no clinical interest, until two of their genes appeared on plasmids in ',False),('Salmonella',True),(' and ',False),('E. coli',True),('. Surveillance that searches for the enzyme family rather than for the ten known alleles would detect the next event earlier.',False)])
P('Several limitations apply. Sampling was one representative per cluster per genus, which captures the breadth of the family but not the within-species diversity that would refine a donor assignment to the level of a strain. The deep nodes of the tree received low bootstrap support, as is usual for a gene family with this much divergence, so the conclusion that mobilisation happened repeatedly rests on the well-supported shallow groupings and on the taxonomic identity of the nearest relatives, not on the deep topology. Synonymous divergence was saturated for two of the progenitor comparisons, which limits what the selection analysis can say about the earliest stages after transfer. The Citrobacter protein that anchors the mcr-9 grouping is a partial sequence of 400 residues and is best regarded as an mcr-9-like gene already present in that genome rather than as an untouched chromosomal progenitor. Finally, the analysis is a comparison of sequences; the enzymatic activity of the candidate reservoir genes, and the level of resistance they would confer if expressed from a plasmid, remain to be tested.',indent=False)

H('5. Conclusions')
RICH([('Every named ',False),('mcr',True),(' family belongs to the chromosomal EptA lineage, and each family entered the mobile gene pool from a different part of it. The catalytic machinery was complete before mobilisation and has been maintained under purifying selection since. What changed was the genomic context, and the chromosomal genes that now sit closest to the mobilised families are found in genera that share environments with food animals and water. Those genes, and the wider EptA clade in ',False),('Aeromonas',True),(', ',False),('Shewanella',True),(', ',False),('Buttiauxella',True),(', ',False),('Vibrio',True),(' and the Moraxellaceae, are where the next mobilised colistin resistance determinant is most likely to originate.',False)])

H('Author contributions')
P('[Initials] designed the study. [Initials] assembled the sequence datasets and performed the phylogenetic, structural and selection analyses. [Initials] carried out the genomic context analysis. [Initials] drafted the manuscript. All authors reviewed and approved the final version.',indent=False)
H('Funding')
P('[Funding statement]',indent=False)
H('Conflict of interest')
P('The authors declare that the research was conducted in the absence of any commercial or financial relationships that could be construed as a potential conflict of interest.',indent=False)

# ---------------- References ----------------
doc.add_page_break()
H('References')
refs=[
"AbuOun, M., Stubberfield, E. J., Duggett, N. A., Kirchner, M., Dormer, L., Nunez-Garcia, J., Randall, L. P., Lemma, F., Crook, D. W., Teale, C., Smith, R. P., & Anjum, M. F. (2017). mcr-1 and mcr-2 variant genes identified in Moraxella species isolated from pigs in Great Britain from 2014 to 2015. Journal of Antimicrobial Chemotherapy, 72(10), 2745–2749. https://doi.org/10.1093/jac/dkx286",
"Capella-Gutiérrez, S., Silla-Martínez, J. M., & Gabaldón, T. (2009). trimAl: A tool for automated alignment trimming in large-scale phylogenetic analyses. Bioinformatics, 25(15), 1972–1973. https://doi.org/10.1093/bioinformatics/btp348",
"Carattoli, A., Villa, L., Feudi, C., Curcio, L., Orsini, S., Luppi, A., Pezzotti, G., & Magistrali, C. F. (2017). Novel plasmid-mediated colistin resistance mcr-4 gene in Salmonella and Escherichia coli, Italy 2013, Spain and Belgium, 2015 to 2016. Euro Surveillance, 22(31), 30589. https://doi.org/10.2807/1560-7917.ES.2017.22.31.30589",
"Carroll, L. M., Gaballa, A., Guldimann, C., Sullivan, G., Henderson, L. O., & Wiedmann, M. (2019). Identification of novel mobilized colistin resistance gene mcr-9 in a multidrug-resistant, colistin-susceptible Salmonella enterica serotype Typhimurium isolate. mBio, 10(3), e00853-19. https://doi.org/10.1128/mBio.00853-19",
"Coates, K., Walsh, T. R., Spencer, J., & Hinchliffe, P. (2017). 1.12 Å resolution crystal structure of the catalytic domain of the plasmid-mediated colistin resistance determinant MCR-2. Acta Crystallographica Section F, 73(8), 443–449. https://doi.org/10.1107/S2053230X17009669",
"Cock, P. J. A., Antao, T., Chang, J. T., Chapman, B. A., Cox, C. J., Dalke, A., Friedberg, I., Hamelryck, T., Kauff, F., Wilczynski, B., & de Hoon, M. J. L. (2009). Biopython: Freely available Python tools for computational molecular biology and bioinformatics. Bioinformatics, 25(11), 1422–1423. https://doi.org/10.1093/bioinformatics/btp163",
"Cullen, T. W., Madsen, J. A., Ivanov, P. L., Brodbelt, J. S., & Trent, M. S. (2011). Characterization of unique modification of flagellar rod protein FlgG by Campylobacter jejuni lipid A phosphoethanolamine transferase, linking bacterial locomotion and antimicrobial peptide resistance. Journal of Biological Chemistry, 287(5), 3326–3336. https://doi.org/10.1074/jbc.M111.321737",
"Deorowicz, S., Debudaj-Grabysz, A., & Gudyś, A. (2016). FAMSA: Fast and accurate multiple sequence alignment of huge protein families. Scientific Reports, 6, 33964. https://doi.org/10.1038/srep33964",
"Feldgarden, M., Brover, V., Gonzalez-Escalona, N., Frye, J. G., Haendiges, J., Haft, D. H., Hoffmann, M., Pettengill, J. B., Prasad, A. B., Tillman, G. E., Tyson, G. H., & Klimke, W. (2021). AMRFinderPlus and the Reference Gene Catalog facilitate examination of the genomic links among antimicrobial resistance, stress response, and virulence. Scientific Reports, 11(1), 12728. https://doi.org/10.1038/s41598-021-91456-0",
"Hu, M., Guo, J., Cheng, Q., Yang, Z., Chan, E. W. C., Chen, S., & Hao, Q. (2016). Crystal structure of Escherichia coli originated MCR-1, a phosphoethanolamine transferase for colistin resistance. Scientific Reports, 6, 38793. https://doi.org/10.1038/srep38793",
"Kieffer, N., Nordmann, P., & Poirel, L. (2017). Moraxella species as potential sources of MCR-like polymyxin resistance determinants. Antimicrobial Agents and Chemotherapy, 61(6), e00129-17. https://doi.org/10.1128/AAC.00129-17",
"Le, S. Q., & Gascuel, O. (2008). An improved general amino acid replacement matrix. Molecular Biology and Evolution, 25(7), 1307–1320. https://doi.org/10.1093/molbev/msn067",
"Liu, Y.-Y., Wang, Y., Walsh, T. R., Yi, L.-X., Zhang, R., Spencer, J., Doi, Y., Tian, G., Dong, B., Huang, X., Yu, L.-F., Gu, D., Ren, H., Chen, X., Lv, L., He, D., Zhou, H., Liang, Z., Liu, J.-H., & Shen, J. (2016). Emergence of plasmid-mediated colistin resistance mechanism MCR-1 in animals and human beings in China: A microbiological and molecular biological study. The Lancet Infectious Diseases, 16(2), 161–168. https://doi.org/10.1016/S1473-3099(15)00424-7",
"Ma, G., Zhu, Y., Yu, Z., Ahmad, A., & Zhang, H. (2016). High resolution crystal structure of the catalytic domain of MCR-1. Scientific Reports, 6, 39540. https://doi.org/10.1038/srep39540",
"Nei, M., & Gojobori, T. (1986). Simple methods for estimating the numbers of synonymous and nonsynonymous nucleotide substitutions. Molecular Biology and Evolution, 3(5), 418–426. https://doi.org/10.1093/oxfordjournals.molbev.a040410",
"O’Leary, N. A., Wright, M. W., Brister, J. R., Ciufo, S., Haddad, D., McVeigh, R., Rajput, B., Robbertse, B., Smith-White, B., Ako-Adjei, D., Astashyn, A., Badretdin, A., Bao, Y., Blinkova, O., Brover, V., Chetvernin, V., Choi, J., Cox, E., Ermolaeva, O., … Pruitt, K. D. (2016). Reference sequence (RefSeq) database at NCBI: Current status, taxonomic expansion, and functional annotation. Nucleic Acids Research, 44(D1), D733–D745. https://doi.org/10.1093/nar/gkv1189",
"Piñeiro, C., Abuín, J. M., & Pichel, J. C. (2020). Very Fast Tree: Speeding up the estimation of phylogenies for large alignments through parallelization and vectorization strategies. Bioinformatics, 36(17), 4658–4659. https://doi.org/10.1093/bioinformatics/btaa582",
"Poirel, L., Jayol, A., & Nordmann, P. (2017). Polymyxins: Antibacterial activity, susceptibility testing, and resistance mechanisms encoded by plasmids or chromosomes. Clinical Microbiology Reviews, 30(2), 557–596. https://doi.org/10.1128/CMR.00064-16",
"Poirel, L., Kieffer, N., & Nordmann, P. (2017). Study of ISApl1-mediated mobilization of the colistin resistance gene mcr-1. Antimicrobial Agents and Chemotherapy, 61(7), e00127-17. https://doi.org/10.1128/AAC.00127-17",
"Price, M. N., Dehal, P. S., & Arkin, A. P. (2010). FastTree 2: Approximately maximum-likelihood trees for large alignments. PLoS ONE, 5(3), e9490. https://doi.org/10.1371/journal.pone.0009490",
"Reynolds, C. M., Kalb, S. R., Cotter, R. J., & Raetz, C. R. H. (2005). A phosphoethanolamine transferase specific for the outer 3-deoxy-D-manno-octulosonic acid residue of Escherichia coli lipopolysaccharide. Journal of Biological Chemistry, 280(22), 21202–21211. https://doi.org/10.1074/jbc.M500964200",
"Snesrud, E., He, S., Chandler, M., Dekker, J. P., Hickman, A. B., McGann, P., & Dyda, F. (2016). A model for transposition of the colistin resistance gene mcr-1 by ISApl1. Antimicrobial Agents and Chemotherapy, 60(11), 6973–6976. https://doi.org/10.1128/AAC.01457-16",
"Snesrud, E., McGann, P., & Chandler, M. (2018). The birth and demise of the ISApl1-mcr-1-ISApl1 composite transposon: The vehicle for transferable colistin resistance. mBio, 9(1), e02381-17. https://doi.org/10.1128/mBio.02381-17",
"Tzeng, Y.-L., Ambrose, K. D., Zughaier, S., Zhou, X., Miller, Y. K., Shafer, W. M., & Stephens, D. S. (2005). Cationic antimicrobial peptide resistance in Neisseria meningitidis. Journal of Bacteriology, 187(15), 5387–5396. https://doi.org/10.1128/JB.187.15.5387-5396.2005",
"Wang, C., Feng, Y., Liu, L., Wei, L., Kang, M., & Zong, Z. (2020). Identification of novel mobile colistin resistance gene mcr-10. Emerging Microbes & Infections, 9(1), 508–516. https://doi.org/10.1080/22221751.2020.1732231",
"Wang, X., Wang, Y., Zhou, Y., Li, J., Yin, W., Wang, S., Zhang, S., Shen, J., Shen, Z., & Wang, Y. (2018). Emergence of a novel mobile colistin resistance gene, mcr-8, in NDM-producing Klebsiella pneumoniae. Emerging Microbes & Infections, 7(1), 122. https://doi.org/10.1038/s41426-018-0124-z",
"Wanty, C., Anandan, A., Piek, S., Walshe, J., Ganguly, J., Carlson, R. W., Stubbs, K. A., Kahler, C. M., & Vrielink, A. (2013). The structure of the neisserial lipooligosaccharide phosphoethanolamine transferase A (LptA) required for resistance to polymyxin. Journal of Molecular Biology, 425(18), 3389–3402. https://doi.org/10.1016/j.jmb.2013.06.029",
"Xavier, B. B., Lammens, C., Ruhal, R., Kumar-Singh, S., Butaye, P., Goossens, H., & Malhotra-Kumar, S. (2016). Identification of a novel plasmid-mediated colistin-resistance gene, mcr-2, in Escherichia coli, Belgium, June 2016. Euro Surveillance, 21(27), 30280. https://doi.org/10.2807/1560-7917.ES.2016.21.27.30280",
"Yang, Y.-Q., Li, Y.-X., Lei, C.-W., Zhang, A.-Y., & Wang, H.-N. (2018). Novel plasmid-mediated colistin resistance gene mcr-7.1 in Klebsiella pneumoniae. Journal of Antimicrobial Chemotherapy, 73(7), 1791–1795. https://doi.org/10.1093/jac/dky111",
"Yin, W., Li, H., Shen, Y., Liu, Z., Wang, S., Shen, Z., Zhang, R., Walsh, T. R., Shen, J., & Wang, Y. (2017). Novel plasmid-mediated colistin resistance gene mcr-3 in Escherichia coli. mBio, 8(3), e00543-17. https://doi.org/10.1128/mBio.00543-17",
"Zhao, Y., Meng, Q., Lai, Y., Wang, L., Zhou, D., Dou, C., Gu, Y., Nie, C., Wei, Y., & Cheng, W. (2018). Structural and mechanistic insights into polymyxin resistance mediated by EptC originated from Escherichia coli. The FEBS Journal, 286(4), 750–764. https://doi.org/10.1111/febs.14719",
]
for r in sorted(refs, key=lambda s: s.lower()):
    HANG(r)

# ---------------- Tables and figure legends ----------------
doc.add_page_break()
H('Table 1')
P('Occupancy of catalytic, metal-coordinating and disulfide-forming positions of MCR-1.1 across the dataset. Positions follow MCR-1.1 numbering. Values give the most frequent residue and the percentage of sequences in the group that carry it.',indent=False)
sites=json.load(open('catalytic_sites.json'))
tab=doc.add_table(rows=1,cols=5); tab.style='Table Grid'
hdr=['Position','Role','Mobilised MCR (n = 11)','EptA clade, chromosomal (n = 65)','All chromosomal (n = 150)']
role={'E246':'metal coordination','T285':'catalytic nucleophile','H390':'metal coordination','H395':'metal coordination','D465':'metal coordination','H466':'metal coordination','H478':'active site','K333':'active site','N329':'active site','S284':'adjacent to nucleophile',
 'C281':'disulfide 1','C291':'disulfide 1','C356':'disulfide 2','C364':'disulfide 2','C414':'disulfide 3','C422':'disulfide 3'}
for i,h in enumerate(hdr):
    c=tab.rows[0].cells[i]; c.text=h
    for p in c.paragraphs:
        p.paragraph_format.line_spacing_rule=WD_LINE_SPACING.SINGLE
        for r in p.runs: r.bold=True; r.font.size=Pt(10); r.font.name='Times New Roman'
epta_pct={s['site']:s for s in sites}
import json as _j
asr=_j.load(open('asr_nodes.json'))
order=['E246','C281','S284','T285','C291','N329','K333','C356','C364','H390','H395','C414','C422','D465','H466','H478']
for s in order:
    d=epta_pct[s]
    row=tab.add_row()
    vals=[s,role.get(s,''),'%s (%.0f%%)'%(d['mcr'],d['mcr_pct']),'%s (%.0f%%)'%(d['epta'],d['epta_pct']),'%s (%.0f%%)'%(d['chrom'],d['chrom_pct'])]
    for i,v in enumerate(vals):
        cell=row.cells[i]; cell.text=v
        for p in cell.paragraphs:
            p.paragraph_format.line_spacing_rule=WD_LINE_SPACING.SINGLE
            for r in p.runs: r.font.size=Pt(10); r.font.name='Times New Roman'

doc.add_page_break()
H('Figure legends')
P('Figure 1. Maximum-likelihood phylogeny of 161 phosphoethanolamine transferases. The tree was inferred from 313 trimmed alignment columns under the LG model with gamma-distributed rates and is shown rooted at its midpoint. Tip labels give the accession and the source organism. Mobilised MCR reference alleles are in red, chromosomal members of the EptA clade in blue, the EptB clade in green and the CptA/EptC clade in purple. Filled circles mark bootstrap support of at least 70% from 100 replicates. Triangles mark the chromosomal protein most similar to each mobilised family.',indent=False)
P('Figure 2. Sequence relationships among mobilised and chromosomal proteins. (a) Pairwise amino acid identity between the reference alleles of the eleven mobilised families. (b) Identity of each family to its closest chromosomal homologue, with the source organism given beside each bar.',indent=False)
P('Figure 3. Domain architecture and conservation. (a) Two-domain architecture of MCR-1.1 with catalytic and metal-coordinating residues in red and disulfide-forming cysteines in purple. (b) Kyte and Doolittle hydropathy over a 19-residue window, with the threshold used to call membrane-spanning segments shown as a dashed line. (c) Positional conservation, expressed as one minus normalised Shannon entropy and smoothed over 15 residues, for the mobilised proteins and for each chromosomal clade, mapped onto MCR-1.1 coordinates. Vertical lines mark the positions in panel a.',indent=False)
P('Figure 4. Genomic context of mobilised genes and of a chromosomal donor locus. Arrows show coding sequences drawn to scale within each row and coloured by function. Rows one to six show the original deposits of six mcr families; the last row shows the chromosomal eptA locus of Faucicola osloensis. Row lengths are given at the right.',indent=False)
P('Figure 5. Selection and base composition. (a) Distribution of dN/dS between reference alleles of different families, for the twelve pairs at which the estimator converged. (b) dN/dS between each mobilised gene and the coding sequence of its closest chromosomal relative. (c) G+C content and third-position G+C of the reference allele of each family, with the approximate genomic value for E. coli shown as a dashed line.',indent=False)
P('Supplementary Table S1. Accessions, source organisms, protein lengths, clade assignment, closest mobilised family and identity values for the 150 chromosomal phosphoethanolamine transferases analysed.',indent=False)

# figures appended
doc.add_page_break()
H('Figures')
for i,f in enumerate(['Figure1_phylogeny.png','Figure2_identity.png','Figure3_domains.png','Figure4_synteny.png','Figure5_selection.png'],start=1):
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(6); p.paragraph_format.space_after=Pt(6)
    w = 5.2 if i in (1,4) else 6.3
    p.add_run().add_picture('figures/'+f,width=Inches(w))
    cap=doc.add_paragraph(); cap.alignment=WD_ALIGN_PARAGRAPH.CENTER
    cap.paragraph_format.line_spacing_rule=WD_LINE_SPACING.SINGLE
    r=cap.add_run('Figure %d'%i); r.bold=True; r.font.size=Pt(11)
    if i<5: doc.add_page_break()

out='/mnt/user-data/outputs/Chromosomal_phosphoethanolamine_transferases_manuscript.docx'
doc.save(out)
print('saved',out)
