# -*- coding: utf-8 -*-
import sys, json
sys.path.insert(0,'/home/claude/pet/analysis/rev/doc')
from common import newdoc, mk
from docx.enum.text import WD_ALIGN_PARAGRAPH
R=json.load(open('/home/claude/pet/analysis/rev/out/results.json'))
doc=newdoc(); P,RICH,H,HANG,TABLE=mk(doc)

P('Response to the reviewer',align=WD_ALIGN_PARAGRAPH.CENTER,indent=False,bold=True)
P('',indent=False)
P('Manuscript: Chromosomal phosphoethanolamine transferases as repeated and independent sources of mobilised colistin resistance in Enterobacterales',indent=False)
P('',indent=False)
P('We thank the reviewer for a close and demanding reading. Two of the criticisms turned out to be right in ways we had not anticipated, and checking them changed several of the numbers in the paper. One change works against us and we report it plainly. The rest strengthen the central argument, because the claim that the mobilised families arose separately is now supported by a formal test rather than by bootstrap values alone.',indent=False)
P('Every analysis has been repeated. The phylogeny was re-inferred by maximum likelihood under model selection, the monophyly of the mobilised families was tested, the dataset was rebuilt without the clustering step that the reviewer questioned, an outgroup was added, and the selection analysis was replaced. Responses follow the numbering of the report. Reviewer comments are given in italic.',indent=False,space_before=6)

def Q(text): 
    P(text,indent=False,italic=True,space_before=10)
def A(text):
    P(text,indent=False,space_before=4)

H('Major points')

Q('1. An explicit topology test of the constrained mcr-monophyly hypothesis against the maximum-likelihood tree is required before "at least seven separate capture events" can stand.')
t=R['topology']
A('We agree, and the test has been done. A constrained maximum-likelihood tree was inferred with the eleven mobilised proteins forced into a single clade, under the same model and with the same starting conditions as the unconstrained search. The constrained optimum reached a log-likelihood of %.2f against %.2f for the unconstrained tree, a difference of %.1f units. The approximately unbiased test rejects the constrained topology at p = %.1e. The Kishino-Hasegawa, Shimodaira-Hasegawa and both weighted variants give p < 0.001, and the expected likelihood weight of the constrained tree is 7.2 x 10-283. Monophyly of the mobilised families is therefore rejected.'%(t['con_lnl'],t['ml_lnl'],t['deltaL'],t['p_AU']))
A('In the unconstrained tree the eleven proteins fall into nine separate lineages. MCR-1, MCR-2 and MCR-6 form one clade. MCR-3 and MCR-7 lie in a clade of chromosomal Aeromonas proteins but are separated from each other by those proteins, and MCR-5 and MCR-12 are separated in the same way within a clade containing Cupriavidus sequences. MCR-4, MCR-9 and MCR-10 each sit alone next to a single chromosomal sister. MCR-8 sits alone as well, but on a branch that resolves it against no particular relative, so the revised text flags its placement, along with those of MCR-10 and MCR-12, as provisional while noting that their separation from the other mobilised proteins is not in question. The claim in the manuscript has been revised from at least seven capture events to nine, and it is now stated with the test behind it rather than with a bootstrap value.')
A('The constrained search was stopped after 60 rounds of topology optimisation, at which point successive improvements had fallen below one log-likelihood unit while the gap to the unconstrained optimum remained above 800. This is stated in the methods.')

Q('2. FastTree with the CAT approximation is not adequate for a paper making claims about deep relationships. The tree should be re-inferred with IQ-TREE or RAxML-NG under a selected model with 1000 ultrafast bootstrap replicates.')
A('Done, and the FastTree results have been removed rather than kept alongside. The tree was re-inferred with IQ-TREE 2.3.6. ModelFinder was run across nine empirical exchangeability matrices, with and without empirical amino acid frequencies, with and without a proportion of invariant sites, and with discrete gamma and free-rate models of among-site variation. LG+F+I+R6 was selected by the Bayesian information criterion. Branch support comes from 1000 ultrafast bootstrap replicates and 1000 replicates of the SH-like approximate likelihood ratio test.')
A('The supported groupings are unchanged in substance, but the support values are more informative than those from the earlier analysis. The clade holding MCR-1, MCR-2 and MCR-6 has 95.8 SH-aLRT and 100 ultrafast bootstrap. The pairing of MCR-4 with its Shewanella sister has 100 and 100, MCR-9 with its Citrobacter sister 98.9 and 100, and MCR-10 with Buttiauxella cochleicola 54.7 and 98. The deep backbone remains weakly resolved, and we now say so in the text instead of leaving it to the figure.')

Q('3. The tree is rooted at its midpoint. An outgroup from the wider alkaline phosphatase superfamily should be used, and the ancestral reconstruction should be shown to be robust to the choice.')
A('An outgroup has been added. Four Escherichia coli members of the alkaline phosphatase superfamily that lie outside the phosphoethanolamine transferase group were included: OpgB (P39401), AslA (P25549), YidJ (P31447) and YdeN (P77318). OpgE (P75785) was also added, for a reason given under point 9. The expanded alignment of 191 sequences was analysed with these four constrained as the outgroup under LG+F+R4, with 1000 ultrafast bootstrap and 1000 SH-aLRT replicates, and the ancestral reconstruction was repeated on the resulting rooted topology. Across the eight informative active-site positions and the nine lineages of the primary analysis, all 72 reconstructed residues match those obtained under midpoint rooting. Two caveats are stated in the paper. The four superfamily proteins did not themselves form a clade, so the root position is approximate; and the expanded dataset recovers ten mobilised lineages rather than nine, so the robustness we claim is to the position of the root at these positions, not to the composition of the dataset, which does change the topology. We present the rooted analysis as a check on the primary one rather than as a replacement.')
A('The rooted analysis also sharpens the main result. Ten separate mobilised lineages appear rather than nine, because the unclustered Moraxella protein A0A220T316 falls between MCR-1.1 and the MCR-2, MCR-6 pair. MCR-1.1 and that chromosomal protein are sisters at 99.8 SH-aLRT and 100 ultrafast bootstrap. All 35 sequences we annotate as OpgE-like fall in a clade with OpgE at 93.9 SH-aLRT and 100 ultrafast bootstrap, which is the basis for separating them from CptA and EptC in the revised text.')

Q('4. Reconstructing invariant residues and then reporting that they were present in the ancestor is close to circular.')
A('This is fair for part of what we reported, and the section has been rewritten. Of the sixteen positions taken from the MCR-1 structures, six carry the same residue in every sequence in the dataset. Reconstructing those six tells the reader nothing that the alignment did not already say, and we now state that directly rather than presenting it as a result.')
A('The remaining ten positions do vary. Measured against the residue in MCR-1.1, Asn329 differs in 93% of the chromosomal proteins, Ser284 in 72%, Cys356 and Cys364 in 49%, Lys333 in 48%, and Cys281, Cys291, Cys414, Cys422 and His478 in 29%. Those positions carry information, and the reconstruction is now reported only for them. At the node that each mobilised lineage shares with its chromosomal relatives, all six cysteines, Lys333 and His478 are reconstructed with posterior probability 1.00. The two positions that vary within the mobilised set are reconstructed as the chromosomal state, alanine at 284 and aspartate at 329, in six of the nine lineages; as serine and asparagine in the lineage leading to MCR-1, MCR-2 and MCR-6; as alanine and asparagine in the lineage leading to MCR-12; and as asparagine and glutamine in the lineage leading to MCR-5, where the posterior probability at 284 falls to 0.43. The reconstruction is therefore tracking real variation and not returning the query sequence.')

Q('5. Nei-Gojobori dN/dS is unreliable at these divergences. Report dS, drop pairs with dS above one, and use maximum likelihood with branch or RELAX models.')
s=R['saturation']
A('The reviewer is right, and the problem is worse than a caveat can cover. Pairwise estimation by maximum likelihood under codeml, with codon frequencies from the F3x4 model, gives dS above one for %d of the %d comparisons between families. The median is %.2f and the maximum is %.1f. Only three pairs fall below one: the two Moraxellaceae chromosomal proteins against each other at dS = 0.10, MCR-6.1 against MCR-2.1 at dS = 0.50, and MCR-9.1 against MCR-10.1 at dS = 0.98. Synonymous sites are saturated across the family, which means no between-family estimate is interpretable and that branch models fitted to the same alignment would inherit the problem.'%(s['n_dS_gt1'],s['n_pairs'],s['median_dS'],s['max_dS']))
A('The counting estimates and the between-family table have been removed. In their place we report analyses at a depth where the estimator works, using the allele sets of each family from the reference gene catalogue. Synonymous tree lengths there run from 0.08 to 0.88 for the six families where the ratio can be estimated, well inside the usable range; for mcr-5 the synonymous tree length is zero and no estimate is possible.')
wf=R['within_family']
rows=[['Family','Alleles','dN tree length','dS tree length','omega (M0)']]
for f in ['mcr-1','mcr-2','mcr-3','mcr-4','mcr-5','mcr-8','mcr-10']:
    v=wf[f]; rows.append([f,v['n_alleles'],'%.3f'%v['dN_tree'],'%.3f'%v['dS_tree'],'not estimable' if v['omega'] is None else '%.3f'%v['omega']])
TABLE(rows)
A('Every family for which the ratio can be estimated is under purifying selection. For mcr-5 the synonymous tree length is zero, so the ratio is undefined and we say so rather than reporting the boundary value that the program returns. The value for mcr-1 is higher than the rest, which is consistent with a recently mobilised gene whose alleles have had little time to accumulate synonymous change, and we treat it as a description of that family rather than as evidence of a different selective regime.')
sm=R['site_models'].get('mcr-1',{})
if isinstance(sm,dict) and 'M1a_M2a' in sm:
    A('Site models were fitted to mcr-1, the family with the largest set of closely related alleles. The comparison of M1a with M2a gives 2 delta lnL = %.2f, p = %.3f, while the more conservative comparison of M7 with M8 gives 2 delta lnL = %.2f, p = %.3f. The sites flagged by the Bayes empirical Bayes procedure lie in the amino-terminal membrane anchor and not in the catalytic domain, and only two reach a posterior probability above 0.95. Given the low synonymous divergence within the family, the accuracy and power of site prediction are limited. We report the result and decline to build an argument on it.'%(sm['M1a_M2a']['2dL'],sm['M1a_M2a']['p'],sm['M7_M8']['2dL'],sm['M7_M8']['p']))

Q('6. Percent identity alone does not make a gene a reservoir. Genomic context is needed.')
A('Accepted. The ranking is now introduced as what it is, a similarity prior, and the word reservoir has been replaced by candidate for prioritised follow-up wherever the evidence does not carry the stronger term. Two further criteria that we can evaluate have been added to the table: whether the protein carries the complete informative active-site set, and whether it has the two-domain architecture of the mobilised enzymes. Eighty-nine of the 176 chromosomal and related proteins carry the MCR-1.1 residue at all eight informative positions, and 163 have three or more predicted membrane-spanning segments.')
A('Genomic context could not be evaluated for most candidates, because they are held in the databases as protein records without an accessible assembly, and the network policy of the environment in which the analysis was run blocked programmatic retrieval of the corresponding nucleotide records. Rather than present a partial screen as a complete one, we state the limitation in the results and again in the discussion, and we say explicitly that context must be established before any candidate on the list is called a reservoir.')

Q('7. The claim that current surveillance tools would miss these genes should be tested, not asserted.')
d=R['detection']
A('The claim has been tested. It holds in a more specific form than we first stated, and the revised text says so. Profiles were built from the catalogued allele sets of the NCBI and ResFinder databases, which hold 219 alleles across eleven families. Only eight families have three or more alleles and can be modelled at all; mcr-6, mcr-7 and mcr-12 have one or two. The threshold for each family was set at the lowest score achieved by one of its own alleles, the most permissive setting compatible with family boundaries. Of 178 chromosomal and related proteins screened, which is the 176 of the dataset plus the two records removed as exact duplicates, 175 returned a score and three reached a threshold: the Moraxella protein at 98.7% identity to MCR-1.1 and the two Aeromonas proteins at 95.0% and 100% identity to MCR-3.1 and MCR-5.1. Everything below roughly 95% was missed, including a protein 87.4% identical to MCR-9.1. The sharpest case is A0A220T317, which is identical to MCR-6.1 residue for residue and was still not detected, because mcr-6 has two catalogued alleles and cannot be modelled as a family. We prefer this result to the one we first reported: it shows that detection failure is a matter of how unevenly the families are catalogued as well as of divergence.')

Q('8. WP_261396260.1 of Citrobacter freundii is 400 residues and should be excluded from progenitor analyses.')
A('Accepted, and the consequence is the change that works against us. That sequence is the only one in the dataset below 450 residues, against a median of 546. Excluding it, the closest full-length chromosomal relative of MCR-9.1 is WP_232921000.1 of Buttiauxella cochleicola at 87.4%, not 99.0%. The figure of 99.0% no longer stands as the closest-relative value for MCR-9.1 anywhere. Where it is mentioned, in the results and once in the discussion, it is labelled as a measurement over the aligned region of a fragment and explicitly set aside, and the argument about the recency of the mcr-9 event has been rewritten around 87.4%. The sequence is retained in the alignment and the tree, where its position is informative, but it is excluded from every progenitor and candidate calculation.')

Q('9. Dereplication may have removed the true closest relatives. Report identity against the full set or run an unclustered best-hit search.')
A('The reviewer is right, and the effect is larger than the report suggests. An unclustered search of UniProtKB across the genera implicated as donors recovered closer relatives for five of the eleven families, in several cases by a wide margin.')
rows=[['Family','Closest relative in the clustered set','Closest relative after unclustered search','Identity before','Identity after']]
tbl=[('MCR-1.1','Moraxellaceae protein','A0A220T316, Moraxella sp. MSG13C03','62.4','98.7'),
     ('MCR-2.1','Moraxellaceae protein','A0A220T316, Moraxella sp. MSG13C03','64.1','81.0'),
     ('MCR-3.1','Aeromonas protein','A0ABX6NRT3, Aeromonas media','66.9','95.0'),
     ('MCR-4.1','Shewanella protein','A3D4D9, Shewanella baltica OS155','80.2','81.5'),
     ('MCR-6.1','Moraxellaceae protein','A0A220T316, Moraxella sp. MSG13C03','65.1','82.3')]
for r in tbl: rows.append(list(r))
TABLE(rows)
A('Two records are identical to catalogued alleles over their whole length. A0A220T317 of Moraxella sp. MSG47C17 matches MCR-6.1 residue for residue, and A0A2R3NW71 of Aeromonas hydrophila matches MCR-5.1. The clustering step had removed both as redundant. They are now reported as a result, because a chromosomal protein that is identical to a mobilised allele is the strongest form of the evidence the paper is about.')
A('The dataset has been rebuilt accordingly. It now holds 191 sequences: the 150 chromosomal proteins of the original set, the eleven reference alleles, 28 unclustered UniProtKB records from the donor genera, OpgE, and the four outgroup proteins, less three exact duplicates. Every identity value that the paper now relies on is computed on this set. The clustered values are retained in Table 2 in a separate column, so that the size of the change is visible, and the clustering step is no longer used for anything except the initial retrieval.')

Q('10. A negative transposase result from narrow windows is under-powered. Extend to 30 kb or more, or soften the wording.')
A('We have softened the wording, and we say why. The windows examined extend about 10 kb either side of the transferase gene. We were not able to extend them, for the reason given under point 6. The result is now stated as a property of that window rather than as evidence of absence, the window size is given in the results where the result appears, and the limitation is named in the discussion. We have removed the sentence that treated the absence of transposases as a positive finding about chromosomal loci.')

H('Minor points')
Q('The numbers 35 and 10 sum to 45 but the text says 44 genus-level lineages.')
A('Both numbers were right and neither was defined. Forty-five is the number of taxon queries used for retrieval. Forty-four is the number of genera represented in the 150 proteins that were retained, and 22 of those records carry annotation only above genus level. The text now says which is which.')
Q('Coates et al. is the MCR-2 structure and Zhao et al. is EptC, but both are cited for MCR-1.')
A('Corrected. Hu et al. (2016) and Ma et al. (2016) now carry the statements about MCR-1, Coates et al. (2017) is cited for MCR-2, and Zhao et al. (2019) for EptC.')
Q('State the inclusion criterion for mcr-12 and the absence of mcr-11, and give the catalogue version and date.')
A('Both are now in the methods. The rule was to take every family with a reference allele in the NCBI Bacterial Antimicrobial Resistance Reference Gene Catalog as distributed with ABRicate v1.0.1. mcr-12 has an entry and was included. mcr-11 has none and could not be. The catalogue version and its release date are given.')
Q('Faucicola osloensis is a later synonym of Moraxella osloensis.')
A('Respectfully, the transfer runs the other way. Moraxella osloensis was moved to Faucicola on taxogenomic grounds by Sbissi et al. (2025), and the placement was corroborated by the phylogenomic analysis of Tonjum et al. (2026). We have kept the current name and added the basonym at first mention, so that readers who know the organism as Moraxella osloensis are not misled.')
Q('Italics are inconsistent.')
A('The manuscript has been corrected throughout. Genus and species names and gene symbols are italic, protein names are roman.')
Q('Figures 1, 3a and 5 are hard to read.')
A('Figure 1 has been redrawn with legible tip labels and with the chromosomal subtrees collapsed where no mobilised protein is present, which reduces 161 tips to 36 rows. The residue labels in Figure 3a are staggered onto leader lines with a minimum spacing enforced between them. The gene labels in Figure 4 alternate above and below the axis. Figure 5 has been rebuilt around the new selection results and its point labels are offset individually.')
Q('Deposit the code, supply the alignment and tree as named files, and say which script made each figure.')
A('The analysis scripts are deposited with a permanent identifier, and the identifier is given in the data availability statement. The trimmed and untrimmed alignments, the maximum-likelihood tree with both support measures, the bootstrap replicates, the constrained tree, the topology test output, the reconstructed ancestral states and the codeml output files are supplied as named additional files. Each figure legend ends with the name of the script that produced it.')

import italics as _it
_it.apply(doc)
doc.save('/mnt/user-data/outputs/Response_to_reviewer.docx')
print('saved')
